
console.log('SUPABASE_SERVICE_ROLE_KEY exists:', !!process.env.SUPABASE_SERVICE_ROLE_KEY);
console.log('NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY exists:', !!process.env.NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY);
