-- 1. Users Table (RBAC)
CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  "canAccessDashboard" BOOLEAN DEFAULT TRUE,
  "canAccessClients" BOOLEAN DEFAULT FALSE,
  "canAccessProcesses" BOOLEAN DEFAULT FALSE,
  "canAccessFinance" BOOLEAN DEFAULT FALSE,
  "canAccessCashFlow" BOOLEAN DEFAULT FALSE,
  "canAccessProducts" BOOLEAN DEFAULT FALSE,
  "canAccessIndicators" BOOLEAN DEFAULT FALSE,
  "canAccessReports" BOOLEAN DEFAULT FALSE,
  "canAccessAudit" BOOLEAN DEFAULT FALSE,
  "canAccessUsers" BOOLEAN DEFAULT FALSE,
  "canAccessDocuments" BOOLEAN DEFAULT FALSE,
  "canAccessDocTemplates" BOOLEAN DEFAULT FALSE,
  "canAccessDocGeneration" BOOLEAN DEFAULT FALSE,
  "canAccessSettings" BOOLEAN DEFAULT FALSE,
  "canAccessProdEnv" BOOLEAN DEFAULT TRUE,
  "canAccessTestEnv" BOOLEAN DEFAULT FALSE,
  "canAccessLawyers" BOOLEAN DEFAULT FALSE,
  is_superadmin BOOLEAN DEFAULT FALSE,
  expiration_date DATE,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add columns if they don't exist (for existing databases)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessDashboard') THEN
      ALTER TABLE users ADD COLUMN "canAccessDashboard" BOOLEAN DEFAULT TRUE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessClients') THEN
      ALTER TABLE users ADD COLUMN "canAccessClients" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessProcesses') THEN
      ALTER TABLE users ADD COLUMN "canAccessProcesses" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessFinance') THEN
      ALTER TABLE users ADD COLUMN "canAccessFinance" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessCashFlow') THEN
      ALTER TABLE users ADD COLUMN "canAccessCashFlow" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessProducts') THEN
      ALTER TABLE users ADD COLUMN "canAccessProducts" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessIndicators') THEN
      ALTER TABLE users ADD COLUMN "canAccessIndicators" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessReports') THEN
      ALTER TABLE users ADD COLUMN "canAccessReports" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessAudit') THEN
      ALTER TABLE users ADD COLUMN "canAccessAudit" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessUsers') THEN
      ALTER TABLE users ADD COLUMN "canAccessUsers" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessDocuments') THEN
      ALTER TABLE users ADD COLUMN "canAccessDocuments" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessDocTemplates') THEN
      ALTER TABLE users ADD COLUMN "canAccessDocTemplates" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessDocGeneration') THEN
      ALTER TABLE users ADD COLUMN "canAccessDocGeneration" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessSettings') THEN
      ALTER TABLE users ADD COLUMN "canAccessSettings" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessProdEnv') THEN
      ALTER TABLE users ADD COLUMN "canAccessProdEnv" BOOLEAN DEFAULT TRUE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessTestEnv') THEN
      ALTER TABLE users ADD COLUMN "canAccessTestEnv" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessLawyers') THEN
      ALTER TABLE users ADD COLUMN "canAccessLawyers" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'is_superadmin') THEN
      ALTER TABLE users ADD COLUMN is_superadmin BOOLEAN DEFAULT FALSE;
  END IF;
END $$;

-- 2. Clients Table
CREATE TABLE IF NOT EXISTS clients (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  address TEXT,
  "addressNumber" TEXT,
  "addressComplement" TEXT,
  neighborhood TEXT,
  city TEXT,
  uf TEXT,
  cep TEXT,
  status TEXT DEFAULT 'Ativo',
  type TEXT DEFAULT 'Pessoa Física',
  document TEXT,
  "inssPassword" TEXT,
  "civilStatus" TEXT,
  profession TEXT,
  "birthDate" DATE,
  "pisNisNit" TEXT,
  "contractSigned" BOOLEAN DEFAULT FALSE,
  "proxySigned" BOOLEAN DEFAULT FALSE,
  "isMinor" BOOLEAN DEFAULT FALSE,
  "legalRepresentative" TEXT,
  photo_url TEXT,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(document, environment)
);

-- 3. Indicators Table
CREATE TABLE IF NOT EXISTS indicators (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  phone TEXT,
  cpf TEXT,
  "pixKey" TEXT,
  email TEXT,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(cpf, environment)
);

-- Add data_nascimento to indicators table
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'indicators' AND column_name = 'data_nascimento') THEN
      ALTER TABLE indicators ADD COLUMN data_nascimento DATE;
  END IF;
END $$;

-- 4. Law Areas Table
CREATE TABLE IF NOT EXISTS law_areas (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(name, environment)
);

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  law_area_id BIGINT REFERENCES law_areas(id) ON DELETE SET NULL,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Contracts Table
CREATE TABLE IF NOT EXISTS contracts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  product TEXT DEFAULT 'Não informado',
  "lawArea" TEXT DEFAULT 'Não informada',
  status TEXT DEFAULT 'Aberto', -- 'Aberto', 'Parcial', 'Quitado', 'Cancelado'
  "launchDate" DATE,
  "contractDate" DATE,
  "processNumber" TEXT,
  "contractValue" DECIMAL(12,2) NOT NULL DEFAULT 0,
  "paymentMethod" TEXT, -- 'À vista', 'Parcelado'
  "installmentsCount" INTEGER DEFAULT 1,
  "isProBono" BOOLEAN DEFAULT FALSE,
  "isFinanced" BOOLEAN DEFAULT FALSE,
  "contractSigned" BOOLEAN DEFAULT FALSE,
  "proxySigned" BOOLEAN DEFAULT FALSE,
  "inssProtocol" TEXT,
  "gpsGenerated" BOOLEAN DEFAULT FALSE,
  "gpsPaid" BOOLEAN DEFAULT FALSE,
  "inssDeferred" BOOLEAN DEFAULT FALSE,
  "childbirthDate" DATE,
  indicator_id BIGINT REFERENCES indicators(id) ON DELETE SET NULL,
  "commissionPercent" DECIMAL(5,2) DEFAULT 0,
  "commissionValue" DECIMAL(12,2) DEFAULT 0,
  "commissionPaid" BOOLEAN DEFAULT FALSE,
  "amountReceivable" DECIMAL(12,2) DEFAULT 0,
  "amountReceived" DECIMAL(12,2) DEFAULT 0,
  observations TEXT,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Installments Table
CREATE TABLE IF NOT EXISTS installments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  contract_id BIGINT REFERENCES contracts(id) ON DELETE CASCADE,
  "installmentNumber" INTEGER NOT NULL,
  "dueDate" DATE NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  "amountPaid" DECIMAL(12,2) DEFAULT 0,
  status TEXT DEFAULT 'Aberto', -- 'Aberto', 'Parcial', 'Quitado', 'Cancelado', 'Prorrogada', 'Atrasada'
  interest DECIMAL(12,2) DEFAULT 0,
  fine DECIMAL(12,2) DEFAULT 0,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Processes Table (Legacy/External Tracking)
CREATE TABLE IF NOT EXISTS processes (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  number TEXT NOT NULL,
  court TEXT,
  priority TEXT,
  client TEXT,
  type TEXT,
  status TEXT,
  "last_update" TEXT,
  "deadline_date" DATE,
  history JSONB DEFAULT '[]',
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(number, environment)
);

-- 9. Bank Accounts Table
CREATE TABLE IF NOT EXISTS bank_accounts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  type TEXT DEFAULT 'Corrente',
  initial_balance DECIMAL(12,2) DEFAULT 0,
  current_balance DECIMAL(12,2) DEFAULT 0,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Financial Categories Table
CREATE TABLE IF NOT EXISTS financial_categories (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  type TEXT NOT NULL, -- 'income', 'expense'
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. Financial Transactions Table
CREATE TABLE IF NOT EXISTS financial_transactions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  amount DECIMAL(12,2) NOT NULL,
  type TEXT NOT NULL, -- 'income', 'expense', 'transfer'
  account_id BIGINT REFERENCES bank_accounts(id) ON DELETE CASCADE,
  category_id BIGINT REFERENCES financial_categories(id) ON DELETE SET NULL,
  description TEXT,
  destination_account_id BIGINT REFERENCES bank_accounts(id) ON DELETE CASCADE,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 12. Payments Table (Installment Payments History)
CREATE TABLE IF NOT EXISTS payments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  installment_id BIGINT REFERENCES installments(id) ON DELETE CASCADE,
  amount DECIMAL(12,2) NOT NULL,
  type TEXT DEFAULT 'payment', -- 'payment', 'reversal'
  payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
  account_id BIGINT REFERENCES bank_accounts(id) ON DELETE SET NULL,
  category_id BIGINT REFERENCES financial_categories(id) ON DELETE SET NULL,
  description TEXT,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 12. Audit Logs Table
CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  table_name TEXT NOT NULL,
  record_id TEXT, -- Permitir nulo para tabelas sem ID único (ex: tabelas de junção)
  action TEXT NOT NULL,
  old_data JSONB,
  new_data JSONB,
  changed_fields JSONB,
  performed_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  performed_at TIMESTAMPTZ DEFAULT NOW(),
  environment TEXT DEFAULT 'production'
);

-- 13. Logical Isolation & Audit Columns (Fallback for existing tables)
DO $$
DECLARE
  t text;
  tables text[] := ARRAY['users', 'clients', 'indicators', 'law_areas', 'products', 'contracts', 'installments', 'processes', 'bank_accounts', 'financial_categories', 'financial_transactions', 'audit_logs', 'roles', 'permissions', 'role_permissions', 'user_roles'];
BEGIN
  -- Fix identity columns to allow upserts
  FOREACH t IN ARRAY tables
  LOOP
    BEGIN
      EXECUTE format('ALTER TABLE %I ALTER COLUMN id SET GENERATED BY DEFAULT', t);
    EXCEPTION WHEN OTHERS THEN
      -- Ignore if already BY DEFAULT or column doesn't exist
    END;
  END LOOP;

  -- Fix audit_logs record_id constraint
  ALTER TABLE audit_logs ALTER COLUMN record_id DROP NOT NULL;

  -- Fix junction tables for audit system
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'role_permissions') THEN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'role_permissions' AND column_name = 'id') THEN
      ALTER TABLE role_permissions ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
      ALTER TABLE role_permissions DROP CONSTRAINT IF EXISTS role_permissions_pkey;
      ALTER TABLE role_permissions ADD PRIMARY KEY (id);
      ALTER TABLE role_permissions ADD CONSTRAINT role_permissions_role_id_permission_id_key UNIQUE (role_id, permission_id);
    END IF;
  END IF;

  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'user_roles') THEN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'user_roles' AND column_name = 'id') THEN
      ALTER TABLE user_roles ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
      ALTER TABLE user_roles DROP CONSTRAINT IF EXISTS user_roles_pkey;
      ALTER TABLE user_roles ADD PRIMARY KEY (id);
      ALTER TABLE user_roles ADD CONSTRAINT user_roles_user_id_role_id_key UNIQUE (user_id, role_id);
    END IF;
  END IF;

  tables := ARRAY['users', 'clients', 'indicators', 'law_areas', 'products', 'contracts', 'installments', 'processes', 'bank_accounts', 'financial_categories', 'financial_transactions', 'audit_logs', 'roles', 'permissions', 'role_permissions', 'user_roles'];
  FOREACH t IN ARRAY tables
  LOOP
    EXECUTE format('ALTER TABLE %I ADD COLUMN IF NOT EXISTS environment TEXT DEFAULT ''production''', t);
    EXECUTE format('UPDATE %I SET environment = ''production'' WHERE environment IS NULL', t);
    EXECUTE format('ALTER TABLE %I ADD COLUMN IF NOT EXISTS created_by BIGINT REFERENCES users(id) ON DELETE SET NULL', t);
    EXECUTE format('ALTER TABLE %I ADD COLUMN IF NOT EXISTS updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL', t);
  END LOOP;
END $$;

-- 14. Audit System (Function & Triggers)
CREATE OR REPLACE FUNCTION log_audit_event()
RETURNS TRIGGER AS $$
DECLARE
  old_data JSONB;
  new_data JSONB;
  changed_fields JSONB;
  performed_by BIGINT;
  record_id TEXT;
  v_env TEXT;
BEGIN
  IF (TG_OP = 'INSERT') THEN
    new_data = to_jsonb(NEW);
    old_data = null;
    changed_fields = null;
    
    IF new_data ? 'created_by' THEN
      performed_by = (new_data->>'created_by')::BIGINT;
    ELSE
      performed_by = NULL;
    END IF;
    
    IF new_data ? 'environment' AND new_data->>'environment' IS NOT NULL THEN
      v_env = new_data->>'environment';
    ELSE
      v_env = 'production';
    END IF;
    
    record_id = new_data->>'id';
  ELSIF (TG_OP = 'UPDATE') THEN
    new_data = to_jsonb(NEW);
    old_data = to_jsonb(OLD);
    SELECT jsonb_object_agg(key, value) INTO changed_fields
    FROM jsonb_each(new_data)
    WHERE old_data->key IS DISTINCT FROM value;
    
    IF new_data ? 'updated_by' THEN
      performed_by = (new_data->>'updated_by')::BIGINT;
    ELSIF new_data ? 'created_by' THEN
      performed_by = (new_data->>'created_by')::BIGINT;
    ELSE
      performed_by = NULL;
    END IF;
    
    IF new_data ? 'environment' AND new_data->>'environment' IS NOT NULL THEN
      v_env = new_data->>'environment';
    ELSE
      v_env = 'production';
    END IF;
    
    record_id = new_data->>'id';
  ELSIF (TG_OP = 'DELETE') THEN
    new_data = null;
    old_data = to_jsonb(OLD);
    changed_fields = null;
    performed_by = NULL;
    
    IF old_data ? 'environment' AND old_data->>'environment' IS NOT NULL THEN
      v_env = old_data->>'environment';
    ELSE
      v_env = 'production';
    END IF;
    
    record_id = old_data->>'id';
  END IF;

  INSERT INTO audit_logs (table_name, record_id, action, old_data, new_data, changed_fields, performed_by, environment)
  VALUES (TG_TABLE_NAME, record_id, TG_OP, old_data, new_data, changed_fields, performed_by, v_env);

  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Apply Audit Triggers
DO $$
DECLARE
  t text;
BEGIN
  FOR t IN SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE' AND table_name != 'audit_logs' AND table_name != 'system_settings'
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS audit_%I ON %I', t, t);
    EXECUTE format('CREATE TRIGGER audit_%I AFTER INSERT OR UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION log_audit_event()', t, t);
  END LOOP;
END $$;

-- 15. Cash Flow Balance System (Function & Trigger)
CREATE OR REPLACE FUNCTION update_account_balance()
RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    IF (NEW.type = 'income') THEN
      UPDATE bank_accounts SET current_balance = current_balance + NEW.amount WHERE id = NEW.account_id;
    ELSIF (NEW.type = 'expense') THEN
      UPDATE bank_accounts SET current_balance = current_balance - NEW.amount WHERE id = NEW.account_id;
    ELSIF (NEW.type = 'transfer') THEN
      UPDATE bank_accounts SET current_balance = current_balance - NEW.amount WHERE id = NEW.account_id;
      UPDATE bank_accounts SET current_balance = current_balance + NEW.amount WHERE id = NEW.destination_account_id;
    END IF;
  ELSIF (TG_OP = 'DELETE') THEN
    IF (OLD.type = 'income') THEN
      UPDATE bank_accounts SET current_balance = current_balance - OLD.amount WHERE id = OLD.account_id;
    ELSIF (OLD.type = 'expense') THEN
      UPDATE bank_accounts SET current_balance = current_balance + OLD.amount WHERE id = OLD.account_id;
    ELSIF (OLD.type = 'transfer') THEN
      UPDATE bank_accounts SET current_balance = current_balance + OLD.amount WHERE id = OLD.account_id;
      UPDATE bank_accounts SET current_balance = current_balance - OLD.amount WHERE id = OLD.destination_account_id;
    END IF;
  ELSIF (TG_OP = 'UPDATE') THEN
    IF (OLD.type = 'income') THEN
      UPDATE bank_accounts SET current_balance = current_balance - OLD.amount WHERE id = OLD.account_id;
    ELSIF (OLD.type = 'expense') THEN
      UPDATE bank_accounts SET current_balance = current_balance + OLD.amount WHERE id = OLD.account_id;
    ELSIF (OLD.type = 'transfer') THEN
      UPDATE bank_accounts SET current_balance = current_balance + OLD.amount WHERE id = OLD.account_id;
      UPDATE bank_accounts SET current_balance = current_balance - OLD.amount WHERE id = OLD.destination_account_id;
    END IF;
    IF (NEW.type = 'income') THEN
      UPDATE bank_accounts SET current_balance = current_balance + NEW.amount WHERE id = NEW.account_id;
    ELSIF (NEW.type = 'expense') THEN
      UPDATE bank_accounts SET current_balance = current_balance - NEW.amount WHERE id = NEW.account_id;
    ELSIF (NEW.type = 'transfer') THEN
      UPDATE bank_accounts SET current_balance = current_balance - NEW.amount WHERE id = NEW.account_id;
      UPDATE bank_accounts SET current_balance = current_balance + NEW.amount WHERE id = NEW.destination_account_id;
    END IF;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_balance ON financial_transactions;
CREATE TRIGGER trigger_update_balance AFTER INSERT OR UPDATE OR DELETE ON financial_transactions FOR EACH ROW EXECUTE FUNCTION update_account_balance();

-- 16. Row Level Security (RLS) & Policies
DO $$
BEGIN
  -- 1. Drop policies that depend on user_id
  EXECUTE 'DROP POLICY IF EXISTS "Usuários podem gerenciar suas próprias tarefas" ON tasks';
  EXECUTE 'DROP POLICY IF EXISTS "Usuários podem ver histórico de suas tarefas" ON task_history';

  -- 2. Alter column type and add environment column
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'tasks' AND column_name = 'user_id' AND data_type = 'uuid') THEN
    ALTER TABLE tasks DROP CONSTRAINT IF EXISTS tasks_user_id_fkey;
    ALTER TABLE tasks ALTER COLUMN user_id TYPE TEXT;
  END IF;
  
  ALTER TABLE tasks ADD COLUMN IF NOT EXISTS environment TEXT DEFAULT 'production';
  UPDATE tasks SET environment = 'production' WHERE environment IS NULL;

  -- 3. Recreate policies
  EXECUTE 'DROP POLICY IF EXISTS "Allow all access to tasks" ON tasks';
  EXECUTE 'CREATE POLICY "Allow all access to tasks" ON tasks FOR ALL USING (true) WITH CHECK (true)';
  EXECUTE 'DROP POLICY IF EXISTS "Allow all access to task_history" ON task_history';
  EXECUTE 'CREATE POLICY "Allow all access to task_history" ON task_history FOR ALL USING (true) WITH CHECK (true)';
END $$;

-- Triggers para Imutabilidade de Contratos e Parcelas Quitadas
CREATE OR REPLACE FUNCTION prevent_update_delete_paid_contract()
RETURNS TRIGGER AS $$
BEGIN
  IF (OLD.status = 'Quitado') THEN
    RAISE EXCEPTION 'Não é possível alterar ou excluir um contrato quitado.';
  END IF;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS prevent_update_delete_paid_contract_trigger ON contracts;
CREATE TRIGGER prevent_update_delete_paid_contract_trigger
BEFORE UPDATE OR DELETE ON contracts
FOR EACH ROW EXECUTE FUNCTION prevent_update_delete_paid_contract();

CREATE OR REPLACE FUNCTION prevent_update_delete_paid_installment()
RETURNS TRIGGER AS $$
BEGIN
  IF (OLD.status = 'Quitado') THEN
    RAISE EXCEPTION 'Não é possível alterar ou excluir uma parcela quitada.';
  END IF;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS prevent_update_delete_paid_installment_trigger ON installments;
CREATE TRIGGER prevent_update_delete_paid_installment_trigger
BEFORE UPDATE OR DELETE ON installments
FOR EACH ROW EXECUTE FUNCTION prevent_update_delete_paid_installment();

DO $$
DECLARE
  t text;
BEGIN
  FOR t IN SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    
    IF t != 'users' AND t != 'tasks' AND t != 'task_history' THEN
      EXECUTE format('DROP POLICY IF EXISTS "Allow all access to %I" ON %I', t, t);
      EXECUTE format('CREATE POLICY "Allow all access to %I" ON %I FOR ALL USING (true) WITH CHECK (true)', t, t);
    END IF;
  END LOOP;
  
  -- Specific policies for users table
  EXECUTE 'DROP POLICY IF EXISTS "Allow all access to users" ON users';
  EXECUTE 'DROP POLICY IF EXISTS "Users can read users" ON users';
  EXECUTE 'DROP POLICY IF EXISTS "Users can insert users" ON users';
  EXECUTE 'DROP POLICY IF EXISTS "Superadmin protected update" ON users';
  EXECUTE 'DROP POLICY IF EXISTS "Superadmin protected delete" ON users';
  
  EXECUTE 'CREATE POLICY "Users can read users" ON users FOR SELECT USING (true)';
  EXECUTE 'CREATE POLICY "Users can insert users" ON users FOR INSERT WITH CHECK ((SELECT is_superadmin FROM users WHERE email = auth.jwt()->>''email'') = TRUE OR is_superadmin IS NOT TRUE)';
  EXECUTE 'CREATE POLICY "Superadmin protected update" ON users FOR UPDATE USING ((SELECT is_superadmin FROM users WHERE email = auth.jwt()->>''email'') = TRUE OR is_superadmin IS NOT TRUE)';
  EXECUTE 'CREATE POLICY "Superadmin protected delete" ON users FOR DELETE USING ((SELECT is_superadmin FROM users WHERE email = auth.jwt()->>''email'') = TRUE OR is_superadmin IS NOT TRUE)';
END $$;

-- 17. Default Data
INSERT INTO users (name, email, password, "canAccessClients", "canAccessProcesses", "canAccessFinance", "canAccessCashFlow", "canAccessProducts", "canAccessIndicators", "canAccessReports", "canAccessAudit", "canAccessUsers", "canAccessDocuments", "canAccessDocTemplates", "canAccessDocGeneration", "canAccessSettings", "canAccessDashboard", "canAccessProdEnv", "canAccessTestEnv")
VALUES ('Administrador', 'admin@admin.com', '$2b$10$9PKydAgjkh6urDnoQ0TsZ.6MDwkQ4TqG7vk/hRyzjur0jfV4ofKVu', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE)
ON CONFLICT (email) DO UPDATE SET
  "canAccessClients" = TRUE,
  "canAccessProcesses" = TRUE,
  "canAccessFinance" = TRUE,
  "canAccessCashFlow" = TRUE,
  "canAccessProducts" = TRUE,
  "canAccessIndicators" = TRUE,
  "canAccessReports" = TRUE,
  "canAccessAudit" = TRUE,
  "canAccessUsers" = TRUE,
  "canAccessDocuments" = TRUE,
  "canAccessDocTemplates" = TRUE,
  "canAccessDocGeneration" = TRUE,
  "canAccessSettings" = TRUE,
  "canAccessDashboard" = TRUE,
  "canAccessProdEnv" = TRUE,
  "canAccessTestEnv" = TRUE;

-- 18. Robust Financial Functions (RPCs) for Transactional Integrity

-- Function to set app environment for RLS
CREATE OR REPLACE FUNCTION set_app_environment(env_name TEXT)
RETURNS void AS $$
BEGIN
  PERFORM set_config('app.current_env', env_name, true);
END;
$$ LANGUAGE plpgsql;

-- Function to process an installment payment
CREATE OR REPLACE FUNCTION process_installment_payment(
  p_installment_id BIGINT,
  p_amount_paid DECIMAL(12,2),
  p_account_id BIGINT,
  p_category_id BIGINT,
  p_date DATE,
  p_description TEXT,
  p_user_id BIGINT,
  p_interest DECIMAL(12,2),
  p_fine DECIMAL(12,2)
) RETURNS JSONB AS $$
DECLARE
  v_installment RECORD;
  v_contract_id BIGINT;
  v_total_due DECIMAL(12,2);
  v_diff DECIMAL(12,2);
  v_new_received DECIMAL(12,2);
  v_new_receivable DECIMAL(12,2);
  v_contract_value DECIMAL(12,2);
  v_new_status TEXT;
  v_all_paid BOOLEAN;
  v_some_paid BOOLEAN;
  v_has_estornado BOOLEAN;
BEGIN
  -- 1. Get installment and contract info
  SELECT * INTO v_installment FROM installments WHERE id = p_installment_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Parcela não encontrada';
  END IF;
  
  v_contract_id := v_installment.contract_id;
  SELECT "contractValue" INTO v_contract_value FROM contracts WHERE id = v_contract_id;

  -- 2. Update current installment
  IF v_installment.status = 'Cancelado' THEN
    RAISE EXCEPTION 'Não é possível pagar uma parcela cancelada';
  END IF;

  v_total_due := (v_installment.amount - COALESCE(v_installment."amountPaid", 0)) + p_interest + p_fine;
  
  IF p_amount_paid >= v_total_due - 0.01 THEN
    -- Full payment
    UPDATE installments 
    SET status = 'Quitado', 
        "amountPaid" = COALESCE("amountPaid", 0) + p_amount_paid, 
        interest = COALESCE(interest, 0) + p_interest, 
        fine = COALESCE(fine, 0) + p_fine,
        updated_by = p_user_id
    WHERE id = p_installment_id;
  ELSE
    -- Partial payment
    UPDATE installments 
    SET status = 'Parcial', 
        "amountPaid" = COALESCE("amountPaid", 0) + p_amount_paid, 
        interest = COALESCE(interest, 0) + p_interest, 
        fine = COALESCE(fine, 0) + p_fine,
        updated_by = p_user_id
    WHERE id = p_installment_id;
  END IF;

  -- 3. Create financial transaction
  -- Note: trigger_update_balance will automatically update the bank account balance
  INSERT INTO financial_transactions (
    date, amount, type, account_id, category_id, description, environment, created_by
  ) VALUES (
    p_date, p_amount_paid, 'income', p_account_id, p_category_id, p_description, v_installment.environment, p_user_id
  );

  -- 4. Create payment record
  INSERT INTO payments (
    installment_id, amount, type, payment_date, account_id, category_id, description, environment, created_by
  ) VALUES (
    p_installment_id, p_amount_paid, 'payment', p_date, p_account_id, p_category_id, p_description, v_installment.environment, p_user_id
  );

  -- 5. Update contract totals and status
  SELECT COALESCE(SUM("amountPaid"), 0) INTO v_new_received FROM installments WHERE contract_id = v_contract_id;
  v_new_receivable := GREATEST(0, v_contract_value - v_new_received);
  
  SELECT 
    bool_and(status IN ('Quitado', 'Cancelado')) AND bool_or(status = 'Quitado'),
    bool_or("amountPaid" > 0),
    bool_or(status = 'Estornado')
  INTO v_all_paid, v_some_paid, v_has_estornado
  FROM installments 
  WHERE contract_id = v_contract_id;

  IF v_has_estornado THEN
    v_new_status := 'Estornado';
  ELSIF v_all_paid THEN
    v_new_status := 'Quitado';
  ELSIF v_some_paid THEN
    v_new_status := 'Parcial';
  ELSE
    v_new_status := 'Aberto';
  END IF;

  UPDATE contracts 
  SET "amountReceived" = v_new_received, 
      "amountReceivable" = v_new_receivable,
      status = v_new_status,
      updated_by = p_user_id
  WHERE id = v_contract_id;

  RETURN jsonb_build_object(
    'success', true,
    'new_received', v_new_received,
    'new_receivable', v_new_receivable,
    'new_status', v_new_status
  );
END;
$$ LANGUAGE plpgsql;

-- Function to process an installment estorno (reversal)
CREATE OR REPLACE FUNCTION process_installment_estorno(
  p_installment_id BIGINT,
  p_reason TEXT,
  p_account_id BIGINT,
  p_user_id BIGINT
) RETURNS JSONB AS $$
DECLARE
  v_installment RECORD;
  v_contract_id BIGINT;
  v_amount_to_reverse DECIMAL(12,2);
  v_new_received DECIMAL(12,2);
  v_new_receivable DECIMAL(12,2);
  v_contract_value DECIMAL(12,2);
  v_new_status TEXT;
  v_all_paid BOOLEAN;
  v_some_paid BOOLEAN;
  v_has_estornado BOOLEAN;
  v_old_obs TEXT;
  v_payment RECORD;
BEGIN
  -- 1. Get installment and contract info
  SELECT * INTO v_installment FROM installments WHERE id = p_installment_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Parcela não encontrada';
  END IF;
  
  IF v_installment."amountPaid" <= 0 THEN
    RAISE EXCEPTION 'Esta parcela não possui valor pago para estornar';
  END IF;

  v_contract_id := v_installment.contract_id;
  SELECT "contractValue", observations INTO v_contract_value, v_old_obs FROM contracts WHERE id = v_contract_id;
  v_amount_to_reverse := v_installment."amountPaid";

  -- 2. Update installment
  UPDATE installments 
  SET status = 'Estornado', 
      "amountPaid" = 0,
      interest = 0,
      fine = 0,
      updated_by = p_user_id
  WHERE id = p_installment_id;

  -- 3. Find the original payment record to delete the corresponding financial transaction
  SELECT * INTO v_payment FROM payments 
  WHERE installment_id = p_installment_id AND type = 'payment' 
  ORDER BY payment_date DESC LIMIT 1;

  IF FOUND THEN
    -- Delete the corresponding financial transaction (income)
    -- The trigger update_account_balance will automatically subtract the amount from the bank account
    DELETE FROM financial_transactions 
    WHERE id IN (
      SELECT id FROM financial_transactions 
      WHERE amount = v_payment.amount 
        AND date = v_payment.payment_date 
        AND account_id = v_payment.account_id 
        AND type = 'income'
        AND environment = v_installment.environment
      ORDER BY id DESC LIMIT 1
    );
  END IF;

  -- 4. Create reversal payment record
  INSERT INTO payments (
    installment_id, amount, type, payment_date, account_id, description, environment, created_by
  ) VALUES (
    p_installment_id, v_amount_to_reverse, 'reversal', CURRENT_DATE, p_account_id, 'Estorno: ' || p_reason, v_installment.environment, p_user_id
  );

  -- 5. Update contract totals and status
  SELECT COALESCE(SUM("amountPaid"), 0) INTO v_new_received FROM installments WHERE contract_id = v_contract_id;
  v_new_receivable := GREATEST(0, v_contract_value - v_new_received);
  
  SELECT 
    bool_and(status IN ('Quitado', 'Cancelado')) AND bool_or(status = 'Quitado'),
    bool_or("amountPaid" > 0),
    bool_or(status = 'Estornado')
  INTO v_all_paid, v_some_paid, v_has_estornado
  FROM installments 
  WHERE contract_id = v_contract_id;

  IF v_has_estornado THEN
    v_new_status := 'Estornado';
  ELSIF v_all_paid THEN
    v_new_status := 'Quitado';
  ELSIF v_some_paid THEN
    v_new_status := 'Parcial';
  ELSE
    v_new_status := 'Aberto';
  END IF;

  UPDATE contracts 
  SET "amountReceived" = v_new_received, 
      "amountReceivable" = v_new_receivable,
      status = v_new_status,
      observations = COALESCE(v_old_obs, '') || E'\n' || '[ESTORNO]: ' || p_reason,
      updated_by = p_user_id
  WHERE id = v_contract_id;

  RETURN jsonb_build_object(
    'success', true,
    'new_received', v_new_received,
    'new_receivable', v_new_receivable,
    'new_status', v_new_status
  );
END;
$$ LANGUAGE plpgsql;

-- Function to process contract cancellation
CREATE OR REPLACE FUNCTION process_contract_cancellation(
  p_contract_id BIGINT,
  p_reason TEXT,
  p_user_id BIGINT
) RETURNS JSONB AS $$
DECLARE
  v_has_payments BOOLEAN;
  v_old_obs TEXT;
BEGIN
  -- 1. Check if there are any invalid installments (paid, reversed, extended, etc.)
  SELECT COALESCE(bool_or("amountPaid" > 0 OR status NOT IN ('Aberto', 'Atrasada')), false) INTO v_has_payments 
  FROM installments 
  WHERE contract_id = p_contract_id;
  
  IF v_has_payments THEN
    RAISE EXCEPTION 'Não é possível cancelar um contrato com parcelas recebidas, estornadas ou prorrogadas.';
  END IF;

  -- 2. Update contract
  SELECT observations INTO v_old_obs FROM contracts WHERE id = p_contract_id;
  
  UPDATE contracts 
  SET status = 'Cancelado',
      observations = COALESCE(v_old_obs, '') || E'\n\n' || '[CANCELAMENTO]: ' || p_reason,
      updated_by = p_user_id
  WHERE id = p_contract_id;

  -- 3. Update all installments
  UPDATE installments 
  SET status = 'Cancelada',
      updated_by = p_user_id
  WHERE contract_id = p_contract_id;

  RETURN jsonb_build_object('success', true);
END;
$$ LANGUAGE plpgsql;

-- 19. Environment Architecture Documentation
/* 
  ARQUITETURA DE AMBIENTES (PRODUÇÃO VS. TESTES):
  
  Este sistema utiliza isolamento lógico por banco de dados.
  1. Conexão Única: O sistema conecta apenas em um banco de dados Supabase (Produção).
  2. Isolamento Lógico: As tabelas possuem uma coluna 'environment' ('production' ou 'test').
  3. Interceptação: O código do sistema (lib/supabase.ts) intercepta as queries e adiciona automaticamente o filtro "WHERE environment = 'test'" ou "WHERE environment = 'production'".
  
  A troca de ambiente é controlada pela variável NEXT_PUBLIC_APP_ENV ou pelo cookie 'app_env'.
*/


-- 20. System Settings Table (Centralized Configuration)
CREATE TABLE IF NOT EXISTS system_settings (
  key VARCHAR(255) NOT NULL,
  value JSONB NOT NULL,
  description TEXT,
  category VARCHAR(50),
  environment VARCHAR(50) NOT NULL DEFAULT 'production',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  PRIMARY KEY (key, environment)
);

-- Enable RLS
ALTER TABLE system_settings ENABLE ROW LEVEL SECURITY;

-- Policies
DO $$
BEGIN
  DROP POLICY IF EXISTS "Everyone can read settings" ON system_settings;
  CREATE POLICY "Everyone can read settings" ON system_settings FOR SELECT USING (true);
  
  DROP POLICY IF EXISTS "Authenticated users can update settings" ON system_settings;
  CREATE POLICY "Authenticated users can update settings" ON system_settings FOR ALL USING (true) WITH CHECK (true);
END $$;

-- Default Data
INSERT INTO system_settings (key, value, description, category, environment)
VALUES
  ('session_timeout', '{"enabled": false, "minutes": 30, "warning_minutes": 5}', 'Configuração de timeout de sessão', 'security', 'production'),
  ('maintenance_mode', '{"enabled": false}', 'Modo de manutenção do sistema', 'system', 'production'),
  ('general_preferences', '{"timezone": "America/Sao_Paulo", "date_format": "DD/MM/YYYY"}', 'Preferências gerais de data e hora', 'general', 'production'),
  ('appearance', '{"theme": "system", "primary_color": "indigo"}', 'Aparência e tema do sistema', 'appearance', 'production')
ON CONFLICT (key, environment) DO NOTHING;

-- Enable Realtime for system_settings
DO $$
BEGIN
  -- 1. Create publication if it doesn't exist
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;

  -- 2. Add table to publication
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE system_settings;
  EXCEPTION
    WHEN duplicate_object THEN
      NULL; -- Table already in publication
    WHEN OTHERS THEN
      NULL; -- Other errors (e.g. publication is FOR ALL TABLES)
  END;
END $$;

-- 21. Security & Performance Improvements (Indexes & Constraints)
-- Indexes for Foreign Keys and Environment
CREATE INDEX IF NOT EXISTS idx_users_environment ON users(environment);
CREATE INDEX IF NOT EXISTS idx_clients_environment ON clients(environment);
CREATE INDEX IF NOT EXISTS idx_contracts_client_id ON contracts(client_id);
CREATE INDEX IF NOT EXISTS idx_contracts_environment ON contracts(environment);
CREATE INDEX IF NOT EXISTS idx_installments_contract_id ON installments(contract_id);
CREATE INDEX IF NOT EXISTS idx_installments_environment ON installments(environment);
CREATE INDEX IF NOT EXISTS idx_transactions_account_id ON financial_transactions(account_id);
CREATE INDEX IF NOT EXISTS idx_transactions_environment ON financial_transactions(environment);
CREATE INDEX IF NOT EXISTS idx_audit_logs_environment ON audit_logs(environment);
CREATE INDEX IF NOT EXISTS idx_audit_logs_record_id ON audit_logs(record_id);

-- Data Integrity Constraints
DO $$
BEGIN
  BEGIN
    ALTER TABLE clients ADD CONSTRAINT check_client_status CHECK (status IN ('Ativo', 'Inativo', 'Bloqueado'));
  EXCEPTION WHEN duplicate_object THEN NULL; END;
  
  BEGIN
    ALTER TABLE contracts DROP CONSTRAINT IF EXISTS check_contract_status;
    ALTER TABLE contracts ADD CONSTRAINT check_contract_status CHECK (status IN ('Aberto', 'Parcial', 'Quitado', 'Cancelado', 'Estornado'));
  EXCEPTION WHEN OTHERS THEN NULL; END;
  
  BEGIN
    ALTER TABLE installments DROP CONSTRAINT IF EXISTS check_installment_status;
    ALTER TABLE installments ADD CONSTRAINT check_installment_status CHECK (status IN ('Aberto', 'Parcial', 'Quitado', 'Cancelado', 'Cancelada', 'Prorrogada', 'Atrasada', 'Estornado'));
  EXCEPTION WHEN OTHERS THEN NULL; END;
  
  BEGIN
    ALTER TABLE financial_transactions ADD CONSTRAINT check_transaction_type CHECK (type IN ('income', 'expense', 'transfer'));
  EXCEPTION WHEN duplicate_object THEN NULL; END;
END $$;

-- 22. RBAC Architecture (Roles & Permissions)
CREATE TABLE IF NOT EXISTS roles (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  description TEXT,
  environment TEXT DEFAULT 'production',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(name, environment)
);

CREATE TABLE IF NOT EXISTS permissions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS role_permissions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  role_id BIGINT REFERENCES roles(id) ON DELETE CASCADE,
  permission_id BIGINT REFERENCES permissions(id) ON DELETE CASCADE,
  UNIQUE(role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS user_roles (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  role_id BIGINT REFERENCES roles(id) ON DELETE CASCADE,
  UNIQUE(user_id, role_id)
);

-- 23. Document Templates & Variables
CREATE TABLE IF NOT EXISTS document_templates (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  category TEXT,
  file_url TEXT NOT NULL,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS template_variables (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  template_id BIGINT REFERENCES document_templates(id) ON DELETE CASCADE,
  variable_tag TEXT NOT NULL,
  data_source_path TEXT NOT NULL,
  data_type TEXT DEFAULT 'String',
  environment TEXT DEFAULT 'production',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for new tables
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE template_variables ENABLE ROW LEVEL SECURITY;

-- Basic Policies for RBAC and Document tables
DO $$
DECLARE
  t text;
BEGIN
  FOR t IN SELECT unnest(ARRAY['roles', 'permissions', 'role_permissions', 'user_roles', 'document_templates', 'template_variables', 'lawyers'])
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS "Allow all access to %I" ON %I', t, t);
    EXECUTE format('CREATE POLICY "Allow all access to %I" ON %I FOR ALL USING (true) WITH CHECK (true)', t, t);
  END LOOP;
END $$;

-- Default Roles & Permissions Setup
INSERT INTO permissions (slug, description) VALUES
  ('access_dashboard', 'Acesso ao Painel'),
  ('access_clients', 'Acesso a Clientes'),
  ('access_processes', 'Acesso a Processos'),
  ('access_finance', 'Acesso ao Financeiro'),
  ('access_cashflow', 'Acesso ao Fluxo de Caixa'),
  ('access_products', 'Acesso a Produtos'),
  ('access_indicators', 'Acesso a Indicadores'),
  ('access_reports', 'Acesso a Relatórios'),
  ('access_audit', 'Acesso a Auditoria'),
  ('access_users', 'Acesso a Usuários'),
  ('access_settings', 'Acesso a Configurações'),
  ('access_documents', 'Acesso a Documentos'),
  ('access_doc_templates', 'Gestão de Modelos de Documentos'),
  ('access_doc_generation', 'Geração de Documentos'),
  ('access_prod_env', 'Acesso ao Ambiente de Produção'),
  ('access_test_env', 'Acesso ao Ambiente de Testes'),
  ('access_lawyers', 'Acesso a Advogados')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO roles (name, description, environment) VALUES
  ('Administrador', 'Acesso total ao sistema', 'production'),
  ('Advogado', 'Acesso a clientes e processos', 'production'),
  ('Financeiro', 'Acesso a financeiro e fluxo de caixa', 'production'),
  ('Estagiário', 'Acesso limitado a clientes e processos', 'production'),
  ('Secretária', 'Acesso a clientes e indicadores', 'production')
ON CONFLICT (name, environment) DO NOTHING;

-- Map Admin Role to All Permissions
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'Administrador'
ON CONFLICT DO NOTHING;

-- Map Admin User to Admin Role
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM users u, roles r
WHERE u.email = 'admin@admin.com' AND r.name = 'Administrador'
ON CONFLICT DO NOTHING;

-- Map Advogado Role to Specific Permissions
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'Advogado' 
AND p.slug IN (
  'access_dashboard', 
  'access_clients', 
  'access_processes', 
  'access_indicators', 
  'access_reports', 
  'access_documents', 
  'access_doc_templates', 
  'access_doc_generation',
  'access_lawyers'
)
ON CONFLICT DO NOTHING;

-- Map Financeiro Role to Specific Permissions
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'Financeiro' 
AND p.slug IN (
  'access_dashboard', 
  'access_finance', 
  'access_cashflow', 
  'access_reports'
)
ON CONFLICT DO NOTHING;

-- Map Estagiário Role to Specific Permissions
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'Estagiário' 
AND p.slug IN (
  'access_dashboard', 
  'access_clients', 
  'access_processes', 
  'access_documents', 
  'access_doc_generation'
)
ON CONFLICT DO NOTHING;

-- Map Secretária Role to Specific Permissions
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'Secretária' 
AND p.slug IN (
  'access_dashboard', 
  'access_clients', 
  'access_indicators'
)
ON CONFLICT DO NOTHING;

-- 18. Client Documents
CREATE TABLE IF NOT EXISTS client_documents (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  file_url TEXT NOT NULL,
  document_type TEXT,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  uploaded_at TIMESTAMPTZ DEFAULT NOW()
);

-- 19. Client Interactions (CRM)
CREATE TABLE IF NOT EXISTS client_interactions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  type TEXT NOT NULL, -- 'Call', 'Email', 'Meeting', 'WhatsApp'
  notes TEXT,
  date TIMESTAMPTZ DEFAULT NOW(),
  environment TEXT DEFAULT 'production',
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL
);

-- 20. Client Tags
CREATE TABLE IF NOT EXISTS client_tags (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  tag TEXT NOT NULL,
  environment TEXT DEFAULT 'production'
);

-- Add new columns to clients
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'clients' AND column_name = 'lgpd_consent') THEN
      ALTER TABLE clients ADD COLUMN lgpd_consent BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'clients' AND column_name = 'lgpd_consent_date') THEN
      ALTER TABLE clients ADD COLUMN lgpd_consent_date TIMESTAMPTZ;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'clients' AND column_name = 'lgpd_source') THEN
      ALTER TABLE clients ADD COLUMN lgpd_source TEXT;
  END IF;
END $$;

-- Add client_id to processes
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'processes' AND column_name = 'client_id') THEN
      ALTER TABLE processes ADD COLUMN client_id BIGINT REFERENCES clients(id) ON DELETE SET NULL;
  END IF;
END $$;

-- 21. Client Onboarding Tokens
CREATE TABLE IF NOT EXISTS client_onboarding_tokens (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  token TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  used BOOLEAN DEFAULT FALSE,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE client_onboarding_tokens ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow insert tokens for testing" ON client_onboarding_tokens;
CREATE POLICY "Allow insert tokens for testing" ON client_onboarding_tokens 
FOR INSERT 
WITH CHECK (true);
DROP POLICY IF EXISTS "Public can read onboarding tokens" ON client_onboarding_tokens;
CREATE POLICY "Public can read onboarding tokens" ON client_onboarding_tokens FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public can update onboarding tokens" ON client_onboarding_tokens;
CREATE POLICY "Public can update onboarding tokens" ON client_onboarding_tokens FOR UPDATE USING (true);

-- 22. Storage Buckets
INSERT INTO storage.buckets (id, name, public)
VALUES ('client_documents', 'client_documents', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Public Access" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can upload" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can update" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can delete" ON storage.objects;

CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'client_documents');
CREATE POLICY "Authenticated users can upload" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'client_documents' AND auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can update" ON storage.objects FOR UPDATE USING (bucket_id = 'client_documents' AND auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can delete" ON storage.objects FOR DELETE USING (bucket_id = 'client_documents' AND auth.role() = 'authenticated');

-- 25. Contract Receivables Summary View
CREATE OR REPLACE VIEW contract_receivables_summary AS
SELECT 
    c.id AS contract_id,
    cl.name AS client_name,
    c."processNumber",
    c."contractValue" AS contract_value,
    c."amountReceived" AS amount_received,
    c."amountReceivable" AS amount_to_receive,
    (SELECT MIN("dueDate") FROM installments WHERE contract_id = c.id AND status NOT IN ('Quitado', 'Cancelada')) AS next_due_date,
    c.status AS contract_status,
    c.environment,
    c.organization_id
FROM 
    contracts c
JOIN 
    clients cl ON c.client_id = cl.id;

-- 26. Payments RLS
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated users to manage payments" ON payments;
CREATE POLICY "Allow authenticated users to manage payments" ON payments
    FOR ALL USING (auth.role() = 'authenticated');
