-- ==============================================================================
-- CORREÇÃO DE PRAZOS E NOTIFICAÇÕES (VERSÃO ROBUSTA V5 - FIX RLS & TYPES)
-- ==============================================================================

-- 0. Garantir colunas e tipos corretos (Nuke and Rebuild se necessário para garantir BIGINT)
DO $body$
BEGIN
  -- Tabela notifications: Se existir e o ID for UUID, precisamos recriar
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'notifications') THEN
    IF (SELECT data_type FROM information_schema.columns 
        WHERE table_name = 'notifications' AND column_name = 'id') = 'uuid' THEN
        DROP TABLE notifications CASCADE;
    END IF;
  END IF;

  -- Tabela process_deadlines: Se existir e o ID for UUID, precisamos recriar
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'process_deadlines') THEN
    IF (SELECT data_type FROM information_schema.columns 
        WHERE table_name = 'process_deadlines' AND column_name = 'id') = 'uuid' THEN
        DROP TABLE process_deadlines CASCADE;
    END IF;
  END IF;
END $body$;

-- 1. Garantir tabelas com a estrutura correta
CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    type TEXT DEFAULT 'info',
    is_read BOOLEAN DEFAULT FALSE,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    environment TEXT DEFAULT 'production',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.process_deadlines (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    process_id BIGINT REFERENCES public.processes(id) ON DELETE CASCADE,
    deadline_date DATE NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'Pendente',
    environment TEXT DEFAULT 'production',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Garantir que user_id em notifications é BIGINT (caso a tabela tenha sido mantida mas com tipo errado)
DO $body$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'notifications' AND column_name = 'user_id') THEN
        IF (SELECT data_type FROM information_schema.columns WHERE table_name = 'notifications' AND column_name = 'user_id') = 'uuid' THEN
            ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_user_id_fkey;
            ALTER TABLE notifications ALTER COLUMN user_id TYPE BIGINT USING NULL;
            ALTER TABLE notifications ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
        END IF;
    END IF;
END $body$;

-- 2. RLS e Políticas (Ajustadas para permitir role 'anon' usada pelo app)
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.process_deadlines ENABLE ROW LEVEL SECURITY;

-- Removemos políticas antigas restritivas
DROP POLICY IF EXISTS "Enable all access for authenticated users" ON public.notifications;
DROP POLICY IF EXISTS "Allow all access to notifications" ON public.notifications;

-- Criamos uma política que permite acesso total (o controle é feito via environment no app)
CREATE POLICY "Public access for notifications" ON public.notifications
    FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Enable all access for authenticated users" ON public.process_deadlines;
DROP POLICY IF EXISTS "Allow all access to process_deadlines" ON public.process_deadlines;

CREATE POLICY "Public access for process_deadlines" ON public.process_deadlines
    FOR ALL USING (true) WITH CHECK (true);

-- 3. Habilitar Realtime
DO $body$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    BEGIN
      ALTER PUBLICATION supabase_realtime DROP TABLE notifications;
    EXCEPTION WHEN OTHERS THEN END;
    ALTER PUBLICATION supabase_realtime ADD TABLE notifications;
  END IF;
END $body$;

-- 4. Função de Notificação Atualizada
CREATE OR REPLACE FUNCTION public.fn_trigger_deadline_notification()
RETURNS TRIGGER AS $body$
DECLARE
    v_user_id BIGINT;
    v_process_number TEXT;
    v_client_name TEXT;
    v_days_remaining INTEGER;
    v_env TEXT;
BEGIN
    -- Busca informações do processo
    SELECT number, client, created_by, environment INTO v_process_number, v_client_name, v_user_id, v_env
    FROM public.processes
    WHERE id = NEW.process_id;

    v_days_remaining := NEW.deadline_date - CURRENT_DATE;

    IF v_days_remaining <= 15 THEN
        INSERT INTO public.notifications (title, message, type, user_id, environment, is_read)
        VALUES (
            'Alerta de Prazo: ' || COALESCE(NEW.description, 'Processo ' || v_process_number),
            'O processo ' || v_process_number || ' (' || v_client_name || ') tem um prazo para ' || 
            to_char(NEW.deadline_date, 'DD/MM/YYYY') || '. Dias restantes: ' || v_days_remaining,
            CASE 
                WHEN v_days_remaining <= 0 THEN 'error'
                WHEN v_days_remaining <= 7 THEN 'warning'
                ELSE 'info'
            END,
            v_user_id,
            COALESCE(NEW.environment, v_env, 'production'),
            FALSE
        );
    END IF;

    RETURN NEW;
END;
$body$ LANGUAGE plpgsql;

-- 5. Trigger
DROP TRIGGER IF EXISTS tr_deadline_notification ON public.process_deadlines;
CREATE TRIGGER tr_deadline_notification
AFTER INSERT OR UPDATE ON public.process_deadlines
FOR EACH ROW EXECUTE FUNCTION public.fn_trigger_deadline_notification();

-- 6. Forçar recarga do cache do esquema
NOTIFY pgrst, 'reload schema';
SELECT pg_notify('pgrst', 'reload schema');
