-- 1. Create Lawyers Table
-- Note: We use 'users(id)' as FK because the app uses a custom users table for RBAC and login.
CREATE TABLE IF NOT EXISTS lawyers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  oab_number TEXT UNIQUE,
  specialty TEXT,
  color_code TEXT,
  is_partner BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Add lawyer_id to processes
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'processes' AND column_name = 'lawyer_id') THEN
      ALTER TABLE processes ADD COLUMN lawyer_id BIGINT REFERENCES lawyers(id) ON DELETE SET NULL;
  END IF;
END $$;

-- 3. Add lawyer_id to contracts
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'contracts' AND column_name = 'lawyer_id') THEN
      ALTER TABLE contracts ADD COLUMN lawyer_id BIGINT REFERENCES lawyers(id) ON DELETE SET NULL;
  END IF;
END $$;

-- 4. Enable RLS
ALTER TABLE lawyers ENABLE ROW LEVEL SECURITY;

-- 5. Add Policies (Permissive as per app standard)
DROP POLICY IF EXISTS "Allow all for lawyers" ON lawyers;
CREATE POLICY "Allow all for lawyers" ON lawyers FOR ALL USING (true) WITH CHECK (true);

-- 6. Apply Audit Trigger
-- We assume log_audit_event() function already exists from previous migrations
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'log_audit_event') THEN
    DROP TRIGGER IF EXISTS audit_lawyers ON lawyers;
    CREATE TRIGGER audit_lawyers AFTER INSERT OR UPDATE OR DELETE ON lawyers FOR EACH ROW EXECUTE FUNCTION log_audit_event();
  END IF;
END $$;

-- 7. Add Permission for Lawyers Management
INSERT INTO permissions (slug, description) 
VALUES ('access_lawyers', 'Acesso a Advogados')
ON CONFLICT (slug) DO NOTHING;

-- 8. Add column to users for direct access
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessLawyers') THEN
      ALTER TABLE users ADD COLUMN "canAccessLawyers" BOOLEAN DEFAULT FALSE;
  END IF;
END $$;
