'use client'

import React, { useState } from 'react'
import { Copy, CheckCircle2, AlertTriangle, Database, ArrowLeft } from 'lucide-react'
import { supabase, getSupabaseConfig } from '@/lib/supabase'
import { getAppEnv } from '@/lib/env'
import Link from 'next/link'

const SQL_SCRIPT = `-- 1. Users Table (RBAC)
CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  "canAccessDashboard" BOOLEAN DEFAULT TRUE,
  "canAccessClients" BOOLEAN DEFAULT FALSE,
  "canAccessProcesses" BOOLEAN DEFAULT FALSE,
  "canAccessFinance" BOOLEAN DEFAULT FALSE,
  "canAccessCashFlow" BOOLEAN DEFAULT FALSE,
  "canAccessProducts" BOOLEAN DEFAULT FALSE,
  "canAccessIndicators" BOOLEAN DEFAULT FALSE,
  "canAccessReports" BOOLEAN DEFAULT FALSE,
  "canAccessAudit" BOOLEAN DEFAULT FALSE,
  "canAccessUsers" BOOLEAN DEFAULT FALSE,
  "canAccessDocuments" BOOLEAN DEFAULT FALSE,
  "canAccessProdEnv" BOOLEAN DEFAULT TRUE,
  "canAccessTestEnv" BOOLEAN DEFAULT FALSE,
  is_superadmin BOOLEAN DEFAULT FALSE,
  expiration_date DATE,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add columns if they don't exist (for existing databases)
DO $body$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessDashboard') THEN
      ALTER TABLE users ADD COLUMN "canAccessDashboard" BOOLEAN DEFAULT TRUE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessClients') THEN
      ALTER TABLE users ADD COLUMN "canAccessClients" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessProcesses') THEN
      ALTER TABLE users ADD COLUMN "canAccessProcesses" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessFinance') THEN
      ALTER TABLE users ADD COLUMN "canAccessFinance" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessCashFlow') THEN
      ALTER TABLE users ADD COLUMN "canAccessCashFlow" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessProducts') THEN
      ALTER TABLE users ADD COLUMN "canAccessProducts" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessIndicators') THEN
      ALTER TABLE users ADD COLUMN "canAccessIndicators" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessReports') THEN
      ALTER TABLE users ADD COLUMN "canAccessReports" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessAudit') THEN
      ALTER TABLE users ADD COLUMN "canAccessAudit" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessUsers') THEN
      ALTER TABLE users ADD COLUMN "canAccessUsers" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessDocuments') THEN
      ALTER TABLE users ADD COLUMN "canAccessDocuments" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessProdEnv') THEN
      ALTER TABLE users ADD COLUMN "canAccessProdEnv" BOOLEAN DEFAULT TRUE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessTestEnv') THEN
      ALTER TABLE users ADD COLUMN "canAccessTestEnv" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'is_superadmin') THEN
      ALTER TABLE users ADD COLUMN is_superadmin BOOLEAN DEFAULT FALSE;
  END IF;
END $body$;

-- 2. Clients Table
CREATE TABLE IF NOT EXISTS clients (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  address TEXT,
  "addressNumber" TEXT,
  "addressComplement" TEXT,
  neighborhood TEXT,
  city TEXT,
  uf TEXT,
  cep TEXT,
  status TEXT DEFAULT 'Ativo',
  type TEXT DEFAULT 'Pessoa Física',
  document TEXT,
  "inssPassword" TEXT,
  "civilStatus" TEXT,
  profession TEXT,
  "birthDate" DATE,
  "pisNisNit" TEXT,
  "contractSigned" BOOLEAN DEFAULT FALSE,
  "proxySigned" BOOLEAN DEFAULT FALSE,
  "isMinor" BOOLEAN DEFAULT FALSE,
  "legalRepresentative" TEXT,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(document, environment)
);

-- 3. Indicators Table
CREATE TABLE IF NOT EXISTS indicators (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  phone TEXT,
  cpf TEXT,
  "pixKey" TEXT,
  email TEXT,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(cpf, environment)
);

-- 4. Law Areas Table
CREATE TABLE IF NOT EXISTS law_areas (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(name, environment)
);

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  law_area_id BIGINT REFERENCES law_areas(id) ON DELETE SET NULL,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Contracts Table
CREATE TABLE IF NOT EXISTS contracts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  product TEXT DEFAULT 'Não informado',
  "lawArea" TEXT DEFAULT 'Não informada',
  status TEXT DEFAULT 'Aberto', -- 'Aberto', 'Parcial', 'Quitado', 'Cancelado'
  "launchDate" DATE,
  "contractDate" DATE,
  "processNumber" TEXT,
  "contractValue" DECIMAL(12,2) NOT NULL DEFAULT 0,
  "paymentMethod" TEXT, -- 'À vista', 'Parcelado'
  "installmentsCount" INTEGER DEFAULT 1,
  "isProBono" BOOLEAN DEFAULT FALSE,
  "isFinanced" BOOLEAN DEFAULT FALSE,
  "contractSigned" BOOLEAN DEFAULT FALSE,
  "proxySigned" BOOLEAN DEFAULT FALSE,
  "inssProtocol" TEXT,
  "gpsGenerated" BOOLEAN DEFAULT FALSE,
  "gpsPaid" BOOLEAN DEFAULT FALSE,
  "inssDeferred" BOOLEAN DEFAULT FALSE,
  "childbirthDate" DATE,
  indicator_id BIGINT REFERENCES indicators(id) ON DELETE SET NULL,
  "commissionPercent" DECIMAL(5,2) DEFAULT 0,
  "commissionValue" DECIMAL(12,2) DEFAULT 0,
  "commissionPaid" BOOLEAN DEFAULT FALSE,
  "amountReceivable" DECIMAL(12,2) DEFAULT 0,
  "amountReceived" DECIMAL(12,2) DEFAULT 0,
  observations TEXT,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Installments Table
CREATE TABLE IF NOT EXISTS installments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  contract_id BIGINT REFERENCES contracts(id) ON DELETE CASCADE,
  "installmentNumber" INTEGER NOT NULL,
  "dueDate" DATE NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  "amountPaid" DECIMAL(12,2) DEFAULT 0,
  status TEXT DEFAULT 'Aberto', -- 'Aberto', 'Parcial', 'Quitado', 'Cancelado', 'Prorrogada', 'Atrasada'
  interest DECIMAL(12,2) DEFAULT 0,
  fine DECIMAL(12,2) DEFAULT 0,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Processes Table (Legacy/External Tracking)
CREATE TABLE IF NOT EXISTS processes (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  number TEXT NOT NULL,
  court TEXT,
  priority TEXT,
  client TEXT,
  type TEXT,
  status TEXT,
  "last_update" TEXT,
  "deadline_date" DATE,
  history JSONB DEFAULT '[]',
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(number, environment)
);

-- 9. Bank Accounts Table
CREATE TABLE IF NOT EXISTS bank_accounts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  type TEXT DEFAULT 'Corrente',
  initial_balance DECIMAL(12,2) DEFAULT 0,
  current_balance DECIMAL(12,2) DEFAULT 0,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Financial Categories Table
CREATE TABLE IF NOT EXISTS financial_categories (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  type TEXT NOT NULL, -- 'income', 'expense'
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. Financial Transactions Table
CREATE TABLE IF NOT EXISTS financial_transactions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  amount DECIMAL(12,2) NOT NULL,
  type TEXT NOT NULL, -- 'income', 'expense', 'transfer'
  account_id BIGINT REFERENCES bank_accounts(id) ON DELETE CASCADE,
  category_id BIGINT REFERENCES financial_categories(id) ON DELETE SET NULL,
  description TEXT,
  destination_account_id BIGINT REFERENCES bank_accounts(id) ON DELETE CASCADE,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 12. Payments Table (Installment Payments History)
CREATE TABLE IF NOT EXISTS payments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  installment_id BIGINT REFERENCES installments(id) ON DELETE CASCADE,
  amount DECIMAL(12,2) NOT NULL,
  type TEXT DEFAULT 'payment', -- 'payment', 'reversal'
  payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
  account_id BIGINT REFERENCES bank_accounts(id) ON DELETE SET NULL,
  category_id BIGINT REFERENCES financial_categories(id) ON DELETE SET NULL,
  description TEXT,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 12. Audit Logs Table
CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  table_name TEXT NOT NULL,
  record_id TEXT NOT NULL,
  action TEXT NOT NULL,
  old_data JSONB,
  new_data JSONB,
  changed_fields JSONB,
  performed_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  performed_at TIMESTAMPTZ DEFAULT NOW(),
  environment TEXT DEFAULT 'production'
);

-- 13. System Settings Table
CREATE TABLE IF NOT EXISTS system_settings (
  key TEXT NOT NULL,
  value JSONB,
  description TEXT,
  category TEXT,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (key, environment)
);

-- 13.1 User Sessions Table
CREATE TABLE IF NOT EXISTS user_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  login_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  logout_at TIMESTAMPTZ,
  ip_address TEXT,
  user_agent TEXT,
  location TEXT,
  environment TEXT NOT NULL DEFAULT 'production'
);

-- 13.2 Login Attempts Table (Brute-force protection)
CREATE TABLE IF NOT EXISTS login_attempts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT NOT NULL,
  ip_address TEXT,
  user_agent TEXT,
  reason TEXT,
  attempted_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 13.3 Notifications Table
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT DEFAULT 'info',
  is_read BOOLEAN DEFAULT FALSE,
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  environment TEXT DEFAULT 'production',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 13.4 Process Deadlines Table
CREATE TABLE IF NOT EXISTS process_deadlines (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  process_id BIGINT REFERENCES processes(id) ON DELETE CASCADE,
  deadline_date DATE NOT NULL,
  description TEXT,
  status TEXT DEFAULT 'Pendente',
  environment TEXT DEFAULT 'production',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 14. Logical Isolation & Audit Columns (Fallback for existing tables)
DO $body$
DECLARE
  t text;
  tables text[] := ARRAY['users', 'clients', 'indicators', 'law_areas', 'products', 'contracts', 'installments', 'processes', 'bank_accounts', 'financial_categories', 'financial_transactions', 'payments', 'audit_logs', 'system_settings', 'user_sessions', 'login_attempts', 'notifications', 'process_deadlines'];
BEGIN
  -- Fix record_id type in audit_logs if it's BIGINT
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'audit_logs' AND column_name = 'record_id' AND data_type = 'bigint') THEN
      ALTER TABLE audit_logs ALTER COLUMN record_id TYPE TEXT;
  END IF;

  -- Fix identity columns to allow upserts
  FOREACH t IN ARRAY tables
  LOOP
    BEGIN
      EXECUTE format('ALTER TABLE %I ALTER COLUMN id SET GENERATED BY DEFAULT', t);
    EXCEPTION WHEN OTHERS THEN
      -- Ignore if already BY DEFAULT or column doesn't exist
    END;
  END LOOP;

  tables := ARRAY['users', 'clients', 'indicators', 'law_areas', 'products', 'contracts', 'installments', 'processes', 'bank_accounts', 'financial_categories', 'financial_transactions', 'payments', 'audit_logs', 'system_settings', 'user_sessions', 'notifications', 'process_deadlines'];
  FOREACH t IN ARRAY tables
  LOOP
    EXECUTE format('ALTER TABLE %I ADD COLUMN IF NOT EXISTS environment TEXT DEFAULT ''production''', t);
    EXECUTE format('UPDATE %I SET environment = ''production'' WHERE environment IS NULL', t);
    EXECUTE format('ALTER TABLE %I ADD COLUMN IF NOT EXISTS created_by BIGINT REFERENCES users(id) ON DELETE SET NULL', t);
    EXECUTE format('ALTER TABLE %I ADD COLUMN IF NOT EXISTS updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL', t);
    
    -- Ensure RLS is enabled
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    
    -- Drop old policies to avoid conflicts
    EXECUTE format('DROP POLICY IF EXISTS "Allow all access to %I" ON %I', t, t);
    
    -- Create permissive policy (logical isolation handled by app)
    EXECUTE format('CREATE POLICY "Allow all access to %I" ON %I FOR ALL USING (true) WITH CHECK (true)', t, t);
  END LOOP;

  -- Fix specific RLS for user_sessions that might have been overridden by audit_hardening.sql
  DROP POLICY IF EXISTS "Enable read access for all users" ON user_sessions;
  DROP POLICY IF EXISTS "Enable insert for authenticated users" ON user_sessions;
  DROP POLICY IF EXISTS "Enable update for authenticated users" ON user_sessions;
  DROP POLICY IF EXISTS "Admin access for user_sessions" ON public.user_sessions;
  DROP POLICY IF EXISTS "User access for user_sessions" ON public.user_sessions;
  DROP POLICY IF EXISTS "Public access for user_sessions" ON public.user_sessions;
  
  CREATE POLICY "Enable read access for all users" ON user_sessions FOR SELECT USING (true);
  CREATE POLICY "Enable insert for all users" ON user_sessions FOR INSERT WITH CHECK (true);
  CREATE POLICY "Enable update for all users" ON user_sessions FOR UPDATE USING (true);
  CREATE POLICY "Enable delete for all users" ON user_sessions FOR DELETE USING (true);
END $body$;

-- 15. Audit System (Function & Triggers)
CREATE OR REPLACE FUNCTION log_audit_event()
RETURNS TRIGGER AS $func$
DECLARE
  old_data JSONB;
  new_data JSONB;
  changed_fields JSONB;
  performed_by BIGINT;
  record_id TEXT;
  v_env TEXT;
BEGIN
  IF (TG_OP = 'INSERT') THEN
    new_data = to_jsonb(NEW);
    old_data = null;
    changed_fields = null;
    
    IF new_data ? 'created_by' THEN
      performed_by = (new_data->>'created_by')::BIGINT;
    ELSE
      performed_by = NULL;
    END IF;
    
    IF new_data ? 'environment' AND new_data->>'environment' IS NOT NULL THEN
      v_env = new_data->>'environment';
    ELSE
      v_env = 'production';
    END IF;
    
    record_id = (new_data->>'id')::TEXT;
  ELSIF (TG_OP = 'UPDATE') THEN
    new_data = to_jsonb(NEW);
    old_data = to_jsonb(OLD);
    SELECT jsonb_object_agg(key, value) INTO changed_fields
    FROM jsonb_each(new_data)
    WHERE old_data->key IS DISTINCT FROM value;
    
    IF new_data ? 'updated_by' THEN
      performed_by = (new_data->>'updated_by')::BIGINT;
    ELSIF new_data ? 'created_by' THEN
      performed_by = (new_data->>'created_by')::BIGINT;
    ELSE
      performed_by = NULL;
    END IF;
    
    IF new_data ? 'environment' AND new_data->>'environment' IS NOT NULL THEN
      v_env = new_data->>'environment';
    ELSE
      v_env = 'production';
    END IF;
    
    record_id = (new_data->>'id')::TEXT;
  ELSIF (TG_OP = 'DELETE') THEN
    new_data = null;
    old_data = to_jsonb(OLD);
    changed_fields = null;
    performed_by = NULL;
    
    IF old_data ? 'environment' AND old_data->>'environment' IS NOT NULL THEN
      v_env = old_data->>'environment';
    ELSE
      v_env = 'production';
    END IF;
    
    record_id = (old_data->>'id')::TEXT;
  END IF;

  INSERT INTO audit_logs (table_name, record_id, action, old_data, new_data, changed_fields, performed_by, environment)
  VALUES (TG_TABLE_NAME, record_id, TG_OP, old_data, new_data, changed_fields, performed_by, v_env);

  RETURN NULL;
END;
$func$ LANGUAGE plpgsql;

-- Apply Audit Triggers
DO $body$
DECLARE
  t text;
BEGIN
  FOR t IN SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_name != 'audit_logs' AND table_name != 'system_settings' AND table_name != 'user_sessions'
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS audit_%I ON %I', t, t);
    EXECUTE format('CREATE TRIGGER audit_%I AFTER INSERT OR UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION log_audit_event()', t, t);
  END LOOP;
END $body$;

-- 14.1 Data Integrity Constraints
DO $body$
BEGIN
  BEGIN
    ALTER TABLE clients ADD CONSTRAINT check_client_status CHECK (status IN ('Ativo', 'Inativo', 'Bloqueado'));
  EXCEPTION WHEN duplicate_object THEN NULL; END;
  
  BEGIN
    ALTER TABLE contracts DROP CONSTRAINT IF EXISTS check_contract_status;
    ALTER TABLE contracts ADD CONSTRAINT check_contract_status CHECK (status IN ('Aberto', 'Parcial', 'Quitado', 'Cancelado', 'Estornado'));
  EXCEPTION WHEN OTHERS THEN NULL; END;
  
  BEGIN
    ALTER TABLE installments DROP CONSTRAINT IF EXISTS check_installment_status;
    ALTER TABLE installments ADD CONSTRAINT check_installment_status CHECK (status IN ('Aberto', 'Parcial', 'Quitado', 'Cancelado', 'Prorrogada', 'Atrasada', 'Estornado'));
  EXCEPTION WHEN OTHERS THEN NULL; END;
  
  BEGIN
    ALTER TABLE financial_transactions ADD CONSTRAINT check_transaction_type CHECK (type IN ('income', 'expense', 'transfer'));
  EXCEPTION WHEN duplicate_object THEN NULL; END;
END $body$;

-- 15. Cash Flow Balance System (Function & Trigger)
CREATE OR REPLACE FUNCTION update_account_balance()
RETURNS TRIGGER AS $func$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    IF (NEW.type = 'income') THEN
      UPDATE bank_accounts SET current_balance = current_balance + NEW.amount WHERE id = NEW.account_id;
    ELSIF (NEW.type = 'expense') THEN
      UPDATE bank_accounts SET current_balance = current_balance - NEW.amount WHERE id = NEW.account_id;
    ELSIF (NEW.type = 'transfer') THEN
      UPDATE bank_accounts SET current_balance = current_balance - NEW.amount WHERE id = NEW.account_id;
      UPDATE bank_accounts SET current_balance = current_balance + NEW.amount WHERE id = NEW.destination_account_id;
    END IF;
  ELSIF (TG_OP = 'DELETE') THEN
    IF (OLD.type = 'income') THEN
      UPDATE bank_accounts SET current_balance = current_balance - OLD.amount WHERE id = OLD.account_id;
    ELSIF (OLD.type = 'expense') THEN
      UPDATE bank_accounts SET current_balance = current_balance + OLD.amount WHERE id = OLD.account_id;
    ELSIF (OLD.type = 'transfer') THEN
      UPDATE bank_accounts SET current_balance = current_balance + OLD.amount WHERE id = OLD.account_id;
      UPDATE bank_accounts SET current_balance = current_balance - OLD.amount WHERE id = OLD.destination_account_id;
    END IF;
  ELSIF (TG_OP = 'UPDATE') THEN
    IF (OLD.type = 'income') THEN
      UPDATE bank_accounts SET current_balance = current_balance - OLD.amount WHERE id = OLD.account_id;
    ELSIF (OLD.type = 'expense') THEN
      UPDATE bank_accounts SET current_balance = current_balance + OLD.amount WHERE id = OLD.account_id;
    ELSIF (OLD.type = 'transfer') THEN
      UPDATE bank_accounts SET current_balance = current_balance + OLD.amount WHERE id = OLD.account_id;
      UPDATE bank_accounts SET current_balance = current_balance - OLD.amount WHERE id = OLD.destination_account_id;
    END IF;
    IF (NEW.type = 'income') THEN
      UPDATE bank_accounts SET current_balance = current_balance + NEW.amount WHERE id = NEW.account_id;
    ELSIF (NEW.type = 'expense') THEN
      UPDATE bank_accounts SET current_balance = current_balance - NEW.amount WHERE id = NEW.account_id;
    ELSIF (NEW.type = 'transfer') THEN
      UPDATE bank_accounts SET current_balance = current_balance - NEW.amount WHERE id = NEW.account_id;
      UPDATE bank_accounts SET current_balance = current_balance + NEW.amount WHERE id = NEW.destination_account_id;
    END IF;
  END IF;
  RETURN NULL;
END;
$func$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_balance ON financial_transactions;
CREATE TRIGGER trigger_update_balance AFTER INSERT OR UPDATE OR DELETE ON financial_transactions FOR EACH ROW EXECUTE FUNCTION update_account_balance();

-- 16. Row Level Security (RLS) & Policies
DO $body$
DECLARE
  t text;
BEGIN
  FOR t IN SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    
    IF t != 'users' THEN
      EXECUTE format('DROP POLICY IF EXISTS "Allow all access to %I" ON %I', t, t);
      EXECUTE format('CREATE POLICY "Allow all access to %I" ON %I FOR ALL USING (true) WITH CHECK (true)', t, t);
    END IF;
  END LOOP;
  
  -- Specific policies for users table
  EXECUTE 'DROP POLICY IF EXISTS "Allow all access to users" ON users';
  EXECUTE 'DROP POLICY IF EXISTS "Users can read users" ON users';
  EXECUTE 'DROP POLICY IF EXISTS "Users can insert users" ON users';
  EXECUTE 'DROP POLICY IF EXISTS "Superadmin protected update" ON users';
  EXECUTE 'DROP POLICY IF EXISTS "Superadmin protected delete" ON users';
  
  EXECUTE 'CREATE POLICY "Users can read users" ON users FOR SELECT USING (true)';
  EXECUTE 'CREATE POLICY "Users can insert users" ON users FOR INSERT WITH CHECK ((SELECT is_superadmin FROM users WHERE email = auth.jwt()->>''email'') = TRUE OR is_superadmin IS NOT TRUE)';
  EXECUTE 'CREATE POLICY "Superadmin protected update" ON users FOR UPDATE USING ((SELECT is_superadmin FROM users WHERE email = auth.jwt()->>''email'') = TRUE OR is_superadmin IS NOT TRUE)';
  EXECUTE 'CREATE POLICY "Superadmin protected delete" ON users FOR DELETE USING ((SELECT is_superadmin FROM users WHERE email = auth.jwt()->>''email'') = TRUE OR is_superadmin IS NOT TRUE)';
END $body$;

-- 17. Default Data
INSERT INTO users (name, email, password, "canAccessClients", "canAccessProcesses", "canAccessFinance", "canAccessCashFlow", "canAccessProducts", "canAccessIndicators", "canAccessReports", "canAccessAudit", "canAccessUsers", "canAccessDocuments", "canAccessDashboard", "canAccessProdEnv", "canAccessTestEnv")
VALUES ('Administrador', 'admin@admin.com', '$2b$10$9PKydAgjkh6urDnoQ0TsZ.6MDwkQ4TqG7vk/hRyzjur0jfV4ofKVu', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE)
ON CONFLICT (email) DO UPDATE SET
  "canAccessClients" = TRUE,
  "canAccessProcesses" = TRUE,
  "canAccessFinance" = TRUE,
  "canAccessCashFlow" = TRUE,
  "canAccessProducts" = TRUE,
  "canAccessIndicators" = TRUE,
  "canAccessReports" = TRUE,
  "canAccessAudit" = TRUE,
  "canAccessUsers" = TRUE,
  "canAccessDocuments" = TRUE,
  "canAccessDashboard" = TRUE,
  "canAccessProdEnv" = TRUE,
  "canAccessTestEnv" = TRUE;

-- 18. Robust Financial Functions (RPCs) for Transactional Integrity

-- Function for partial payment with desdobramento
CREATE OR REPLACE FUNCTION rpc_recebimento_com_desdobramento(
  p_installment_id BIGINT,
  p_valor_principal_pago DECIMAL(12,2),
  p_valor_juros DECIMAL(12,2),
  p_valor_multa DECIMAL(12,2),
  p_account_id BIGINT,
  p_category_id BIGINT,
  p_date DATE,
  p_description TEXT,
  p_user_id BIGINT
) RETURNS JSONB
LANGUAGE plpgsql
AS $func$
DECLARE
  v_installment RECORD;
  v_novo_saldo DECIMAL(12,2);
  v_nova_parcela_id BIGINT;
  v_total_pago DECIMAL(12,2);
BEGIN
  -- 1. Bloquear a linha da parcela original (Row-Level Lock) para evitar concorrência
  SELECT * INTO v_installment
  FROM installments
  WHERE id = p_installment_id
  FOR UPDATE;

  -- Validações de Existência e Status
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Parcela % não encontrada.', p_installment_id;
  END IF;

  IF v_installment.status = 'Quitado' THEN
    RAISE EXCEPTION 'A parcela % já encontra-se quitada e não pode ser desdobrada.', p_installment_id;
  END IF;

  IF v_installment.status = 'Cancelado' THEN
    RAISE EXCEPTION 'Não é possível desdobrar uma parcela cancelada.';
  END IF;

  -- 2. Validação da Regra de Negócio: O principal pago deve ser menor que o original
  IF p_valor_principal_pago >= v_installment.amount THEN
    RAISE EXCEPTION 'O valor principal pago (%) deve ser estritamente menor que o valor original da parcela (%). Para pagamentos integrais, utilize a baixa total.', p_valor_principal_pago, v_installment.amount;
  END IF;

  IF p_valor_principal_pago <= 0 THEN
    RAISE EXCEPTION 'O valor principal pago deve ser maior que zero.';
  END IF;

  -- 3. Calcular o saldo remanescente e o total pago
  v_novo_saldo := v_installment.amount - p_valor_principal_pago;
  v_total_pago := p_valor_principal_pago + p_valor_juros + p_valor_multa;

  -- 4. Atualizar a Parcela Original (Quitar pelo valor pago)
  -- Validação de segurança para p_user_id (evitar violação de FK se o ID for inválido)
  IF p_user_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM users WHERE id = p_user_id) THEN
    p_user_id := NULL;
  END IF;

  UPDATE installments
  SET 
    amount = p_valor_principal_pago,
    "amountPaid" = p_valor_principal_pago,
    interest = p_valor_juros,
    fine = p_valor_multa,
    status = 'Quitado',
    updated_by = p_user_id
  WHERE id = p_installment_id;

  -- 5. Gerar a Parcela Remanescente (EXATAMENTE UMA)
  INSERT INTO installments (
    contract_id,
    "installmentNumber",
    "dueDate",
    amount,
    "amountPaid",
    status,
    interest,
    fine,
    environment,
    created_by,
    updated_by
  ) VALUES (
    v_installment.contract_id,
    v_installment."installmentNumber", -- Mantém o mesmo número de parcela para referência
    v_installment."dueDate",
    v_novo_saldo,
    0,
    'Aberto',
    0,
    0,
    v_installment.environment,
    p_user_id,
    p_user_id
  ) RETURNING id INTO v_nova_parcela_id;

  -- 6. Registrar a Movimentação no Fluxo de Caixa (EXATAMENTE UMA)
  -- Nota: A trigger existente no seu banco (trigger_update_balance) vai atualizar o saldo da conta bancária automaticamente após este insert.
  INSERT INTO financial_transactions (
    date,
    amount,
    type,
    account_id,
    category_id,
    description,
    environment,
    created_by
  ) VALUES (
    p_date,
    v_total_pago,
    'income',
    p_account_id,
    p_category_id,
    p_description,
    v_installment.environment,
    p_user_id
  );

  -- Retorna sucesso e os IDs gerados
  RETURN jsonb_build_object(
    'sucesso', true,
    'mensagem', 'Desdobramento realizado com sucesso.',
    'parcela_original_id', p_installment_id,
    'nova_parcela_id', v_nova_parcela_id
  );

EXCEPTION
  WHEN OTHERS THEN
    -- O PostgreSQL garante o ROLLBACK automático de tudo acima caso caia aqui
    RAISE EXCEPTION 'Erro ao processar desdobramento: %', SQLERRM;
END;
$func$;

-- Function to process an installment payment
CREATE OR REPLACE FUNCTION process_installment_payment(
  p_installment_id BIGINT,
  p_amount_paid DECIMAL(12,2),
  p_account_id BIGINT,
  p_category_id BIGINT,
  p_date DATE,
  p_description TEXT,
  p_user_id BIGINT,
  p_interest DECIMAL(12,2),
  p_fine DECIMAL(12,2)
) RETURNS JSONB AS $func$
DECLARE
  v_installment RECORD;
  v_contract_id BIGINT;
  v_total_due DECIMAL(12,2);
  v_diff DECIMAL(12,2);
  v_new_received DECIMAL(12,2);
  v_new_receivable DECIMAL(12,2);
  v_contract_value DECIMAL(12,2);
  v_new_status TEXT;
  v_all_paid BOOLEAN;
  v_some_paid BOOLEAN;
  v_has_estornado BOOLEAN;
BEGIN
  -- Validação de segurança para p_user_id (evitar violação de FK se o ID for inválido)
  IF p_user_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM users WHERE id = p_user_id) THEN
    p_user_id := NULL;
  END IF;

  -- 1. Get installment and contract info
  SELECT * INTO v_installment FROM installments WHERE id = p_installment_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Parcela não encontrada';
  END IF;
  
  v_contract_id := v_installment.contract_id;
  SELECT "contractValue" INTO v_contract_value FROM contracts WHERE id = v_contract_id;

  -- 2. Update current installment
  IF v_installment.status = 'Cancelado' THEN
    RAISE EXCEPTION 'Não é possível pagar uma parcela cancelada';
  END IF;

  v_total_due := (v_installment.amount - COALESCE(v_installment."amountPaid", 0)) + p_interest + p_fine;
  
  IF p_amount_paid >= v_total_due - 0.01 THEN
    -- Full payment
    UPDATE installments 
    SET status = 'Quitado', 
        "amountPaid" = COALESCE("amountPaid", 0) + p_amount_paid, 
        interest = COALESCE(interest, 0) + p_interest, 
        fine = COALESCE(fine, 0) + p_fine,
        updated_by = p_user_id
    WHERE id = p_installment_id;
  ELSE
    -- Partial payment
    UPDATE installments 
    SET status = 'Parcial', 
        "amountPaid" = COALESCE("amountPaid", 0) + p_amount_paid, 
        interest = COALESCE(interest, 0) + p_interest, 
        fine = COALESCE(fine, 0) + p_fine,
        updated_by = p_user_id
    WHERE id = p_installment_id;
  END IF;

  -- 3. Create financial transaction
  -- Note: trigger_update_balance will automatically update the bank account balance
  INSERT INTO financial_transactions (
    date, amount, type, account_id, category_id, description, environment, created_by
  ) VALUES (
    p_date, p_amount_paid, 'income', p_account_id, p_category_id, p_description, v_installment.environment, p_user_id
  );

  -- 4. Create payment record
  INSERT INTO payments (
    installment_id, amount, type, payment_date, account_id, category_id, description, environment, created_by
  ) VALUES (
    p_installment_id, p_amount_paid, 'payment', p_date, p_account_id, p_category_id, p_description, v_installment.environment, p_user_id
  );

  -- 5. Update contract totals and status
  SELECT COALESCE(SUM("amountPaid"), 0) INTO v_new_received FROM installments WHERE contract_id = v_contract_id;
  v_new_receivable := GREATEST(0, v_contract_value - v_new_received);
  
  SELECT 
    bool_and(status IN ('Quitado', 'Cancelado')) AND bool_or(status = 'Quitado'),
    bool_or("amountPaid" > 0),
    bool_or(status = 'Estornado')
  INTO v_all_paid, v_some_paid, v_has_estornado
  FROM installments 
  WHERE contract_id = v_contract_id;

  IF v_has_estornado THEN
    v_new_status := 'Estornado';
  ELSIF v_all_paid THEN
    v_new_status := 'Quitado';
  ELSIF v_some_paid THEN
    v_new_status := 'Parcial';
  ELSE
    v_new_status := 'Aberto';
  END IF;

  UPDATE contracts 
  SET "amountReceived" = v_new_received, 
      "amountReceivable" = v_new_receivable,
      status = v_new_status,
      updated_by = p_user_id
  WHERE id = v_contract_id;

  RETURN jsonb_build_object(
    'success', true,
    'new_received', v_new_received,
    'new_receivable', v_new_receivable,
    'new_status', v_new_status
  );
END;
$func$ LANGUAGE plpgsql;

-- Function to process an installment estorno (reversal)
CREATE OR REPLACE FUNCTION process_installment_estorno(
  p_installment_id BIGINT,
  p_reason TEXT,
  p_account_id BIGINT,
  p_user_id BIGINT
) RETURNS JSONB AS $func$
DECLARE
  v_installment RECORD;
  v_contract_id BIGINT;
  v_amount_to_reverse DECIMAL(12,2);
  v_new_received DECIMAL(12,2);
  v_new_receivable DECIMAL(12,2);
  v_contract_value DECIMAL(12,2);
  v_new_status TEXT;
  v_all_paid BOOLEAN;
  v_some_paid BOOLEAN;
  v_has_estornado BOOLEAN;
  v_old_obs TEXT;
  v_payment RECORD;
BEGIN
  -- Validação de segurança para p_user_id (evitar violação de FK se o ID for inválido)
  IF p_user_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM users WHERE id = p_user_id) THEN
    p_user_id := NULL;
  END IF;

  -- 1. Get installment and contract info
  SELECT * INTO v_installment FROM installments WHERE id = p_installment_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Parcela não encontrada';
  END IF;
  
  IF v_installment."amountPaid" <= 0 THEN
    RAISE EXCEPTION 'Esta parcela não possui valor pago para estornar';
  END IF;

  v_contract_id := v_installment.contract_id;
  SELECT "contractValue", observations INTO v_contract_value, v_old_obs FROM contracts WHERE id = v_contract_id;
  v_amount_to_reverse := v_installment."amountPaid";

  -- 2. Update installment
  UPDATE installments 
  SET status = 'Estornado', 
      "amountPaid" = 0,
      interest = 0,
      fine = 0,
      updated_by = p_user_id
  WHERE id = p_installment_id;

  -- 3. Find the original payment record to delete the corresponding financial transaction
  SELECT * INTO v_payment FROM payments 
  WHERE installment_id = p_installment_id AND type = 'payment' 
  ORDER BY payment_date DESC LIMIT 1;

  IF FOUND THEN
    -- Delete the corresponding financial transaction (income)
    -- The trigger update_account_balance will automatically subtract the amount from the bank account
    DELETE FROM financial_transactions 
    WHERE id IN (
      SELECT id FROM financial_transactions 
      WHERE amount = v_payment.amount 
        AND date = v_payment.payment_date 
        AND account_id = v_payment.account_id 
        AND type = 'income'
        AND environment = v_installment.environment
      ORDER BY id DESC LIMIT 1
    );
  END IF;

  -- 4. Create reversal payment record
  INSERT INTO payments (
    installment_id, amount, type, payment_date, account_id, description, environment, created_by
  ) VALUES (
    p_installment_id, v_amount_to_reverse, 'reversal', CURRENT_DATE, p_account_id, 'Estorno: ' || p_reason, v_installment.environment, p_user_id
  );

  -- 5. Update contract totals and status
  SELECT COALESCE(SUM("amountPaid"), 0) INTO v_new_received FROM installments WHERE contract_id = v_contract_id;
  v_new_receivable := GREATEST(0, v_contract_value - v_new_received);
  
  SELECT 
    bool_and(status IN ('Quitado', 'Cancelado')) AND bool_or(status = 'Quitado'),
    bool_or("amountPaid" > 0),
    bool_or(status = 'Estornado')
  INTO v_all_paid, v_some_paid, v_has_estornado
  FROM installments 
  WHERE contract_id = v_contract_id;

  IF v_has_estornado THEN
    v_new_status := 'Estornado';
  ELSIF v_all_paid THEN
    v_new_status := 'Quitado';
  ELSIF v_some_paid THEN
    v_new_status := 'Parcial';
  ELSE
    v_new_status := 'Aberto';
  END IF;

  UPDATE contracts 
  SET "amountReceived" = v_new_received, 
      "amountReceivable" = v_new_receivable,
      status = v_new_status,
      observations = COALESCE(v_old_obs, '') || E'\n' || '[ESTORNO]: ' || p_reason,
      updated_by = p_user_id
  WHERE id = v_contract_id;

  RETURN jsonb_build_object(
    'success', true,
    'new_received', v_new_received,
    'new_receivable', v_new_receivable,
    'new_status', v_new_status
  );
END;
$func$ LANGUAGE plpgsql;

-- Function to process contract cancellation
CREATE OR REPLACE FUNCTION process_contract_cancellation(
  p_contract_id BIGINT,
  p_reason TEXT,
  p_user_id BIGINT
) RETURNS JSONB AS $func$
DECLARE
  v_has_payments BOOLEAN;
  v_old_obs TEXT;
BEGIN
  -- Validação de segurança para p_user_id (evitar violação de FK se o ID for inválido)
  IF p_user_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM users WHERE id = p_user_id) THEN
    p_user_id := NULL;
  END IF;

  -- 1. Check if there are any invalid installments (paid, reversed, extended, etc.)
  SELECT COALESCE(bool_or("amountPaid" > 0 OR status NOT IN ('Aberto', 'Atrasada')), false) INTO v_has_payments 
  FROM installments 
  WHERE contract_id = p_contract_id;
  
  IF v_has_payments THEN
    RAISE EXCEPTION 'Não é possível cancelar um contrato com parcelas recebidas ou em status inválido.';
  END IF;

  -- 2. Update contract
  SELECT observations INTO v_old_obs FROM contracts WHERE id = p_contract_id;
  
  UPDATE contracts 
  SET status = 'Cancelado',
      observations = COALESCE(v_old_obs, '') || E'\n\n' || '[CANCELAMENTO]: ' || p_reason,
      updated_by = p_user_id
  WHERE id = p_contract_id;

  -- 3. Update all installments
  UPDATE installments 
  SET status = 'Cancelado',
      updated_by = p_user_id
  WHERE contract_id = p_contract_id;

  RETURN jsonb_build_object('success', true);
END;
$func$ LANGUAGE plpgsql;

-- 19. Environment Architecture Documentation
/* 
  ARQUITETURA DE AMBIENTES (PRODUÇÃO VS. TESTES):
  
  Este sistema utiliza isolamento lógico por banco de dados.
  1. Conexão Única: O sistema conecta apenas em um banco de dados Supabase (Produção).
  2. Isolamento Lógico: As tabelas possuem uma coluna 'environment' ('production' ou 'test').
  3. Interceptação: O código do sistema (lib/supabase.ts) intercepta as queries e adiciona automaticamente o filtro "WHERE environment = 'test'" ou "WHERE environment = 'production'".
  
  A troca de ambiente é controlada pela variável NEXT_PUBLIC_APP_ENV ou pelo cookie 'app_env'.
*/

-- 20. Client Documents
CREATE TABLE IF NOT EXISTS client_documents (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  file_url TEXT NOT NULL,
  document_type TEXT,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  uploaded_at TIMESTAMPTZ DEFAULT NOW()
);

-- 21. Client Interactions (CRM)
CREATE TABLE IF NOT EXISTS client_interactions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  type TEXT NOT NULL, -- 'Call', 'Email', 'Meeting', 'WhatsApp'
  notes TEXT,
  date TIMESTAMPTZ DEFAULT NOW(),
  environment TEXT DEFAULT 'production',
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL
);

-- 22. Client Tags
CREATE TABLE IF NOT EXISTS client_tags (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  tag TEXT NOT NULL,
  environment TEXT DEFAULT 'production'
);

-- Add new columns to clients
DO $body$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'clients' AND column_name = 'lgpd_consent') THEN
      ALTER TABLE clients ADD COLUMN lgpd_consent BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'clients' AND column_name = 'lgpd_consent_date') THEN
      ALTER TABLE clients ADD COLUMN lgpd_consent_date TIMESTAMPTZ;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'clients' AND column_name = 'lgpd_source') THEN
      ALTER TABLE clients ADD COLUMN lgpd_source TEXT;
  END IF;
END $body$;

-- Add client_id to processes
DO $body$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'processes' AND column_name = 'client_id') THEN
      ALTER TABLE processes ADD COLUMN client_id BIGINT REFERENCES clients(id) ON DELETE SET NULL;
  END IF;
END $body$;

-- 23. Client Onboarding Tokens
CREATE TABLE IF NOT EXISTS client_onboarding_tokens (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  token TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  used BOOLEAN DEFAULT FALSE,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE client_onboarding_tokens ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow insert tokens for testing" ON client_onboarding_tokens;
CREATE POLICY "Allow insert tokens for testing" ON client_onboarding_tokens 
FOR INSERT 
WITH CHECK (true);
DROP POLICY IF EXISTS "Public can read onboarding tokens" ON client_onboarding_tokens;
CREATE POLICY "Public can read onboarding tokens" ON client_onboarding_tokens FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public can update onboarding tokens" ON client_onboarding_tokens;
CREATE POLICY "Public can update onboarding tokens" ON client_onboarding_tokens FOR UPDATE USING (true);

-- 24. Storage Buckets
INSERT INTO storage.buckets (id, name, public)
VALUES ('client_documents', 'client_documents', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Public Access" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can upload" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can update" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can delete" ON storage.objects;

CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'client_documents');
CREATE POLICY "Authenticated users can upload" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'client_documents' AND auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can update" ON storage.objects FOR UPDATE USING (bucket_id = 'client_documents' AND auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can delete" ON storage.objects FOR DELETE USING (bucket_id = 'client_documents' AND auth.role() = 'authenticated');

-- 25. Contract Receivables Summary View
CREATE OR REPLACE VIEW contract_receivables_summary AS
SELECT 
    c.id AS contract_id,
    cl.name AS client_name,
    c."processNumber",
    c."contractValue" AS contract_value,
    c."amountReceived" AS amount_received,
    c."amountReceivable" AS amount_to_receive,
    (SELECT MIN("dueDate") FROM installments WHERE contract_id = c.id AND status NOT IN ('Quitado', 'Cancelada')) AS next_due_date,
    c.status AS contract_status,
    c.environment
FROM 
    contracts c
JOIN 
    clients cl ON c.client_id = cl.id;

-- 26. Payments RLS
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow authenticated users to manage payments" ON payments;
CREATE POLICY "Allow authenticated users to manage payments" ON payments
    FOR ALL USING (auth.role() = 'authenticated');

-- 27. Trigger para Recálculo Automático de Contratos
CREATE OR REPLACE FUNCTION fn_recalculate_contract_totals()
RETURNS TRIGGER AS $$
DECLARE
  v_contract_id BIGINT;
  v_total_received DECIMAL(12,2);
  v_contract_value DECIMAL(12,2);
BEGIN
  IF (TG_TABLE_NAME = 'payments') THEN
    SELECT contract_id INTO v_contract_id FROM installments WHERE id = NEW.installment_id;
  ELSIF (TG_TABLE_NAME = 'installments') THEN
    v_contract_id := NEW.contract_id;
  END IF;
  IF v_contract_id IS NULL THEN RETURN NULL; END IF;
  SELECT COALESCE(SUM("amountPaid"), 0) INTO v_total_received FROM installments WHERE contract_id = v_contract_id;
  SELECT "contractValue" INTO v_contract_value FROM contracts WHERE id = v_contract_id;
  UPDATE contracts 
  SET "amountReceived" = v_total_received,
      "amountReceivable" = GREATEST(0, v_contract_value - v_total_received),
      status = CASE WHEN v_total_received >= v_contract_value THEN 'Quitado' WHEN v_total_received > 0 THEN 'Parcial' ELSE 'Aberto' END
  WHERE id = v_contract_id;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_recalculate_contract_on_payment ON payments;
CREATE TRIGGER trg_recalculate_contract_on_payment AFTER INSERT OR UPDATE OR DELETE ON payments FOR EACH ROW EXECUTE FUNCTION fn_recalculate_contract_totals();

DROP TRIGGER IF EXISTS trg_recalculate_contract_on_installment ON installments;
CREATE TRIGGER trg_recalculate_contract_on_installment AFTER UPDATE OF "amountPaid" ON installments FOR EACH ROW EXECUTE FUNCTION fn_recalculate_contract_totals();

-- 28. Correção pontual do contrato 91
UPDATE contracts SET "amountReceived" = 1000.00, "amountReceivable" = 0.00, status = 'Quitado', updated_at = NOW() WHERE id = 91 AND environment = 'test';
`

export default function SetupPage() {
  const env = getAppEnv()
  const config = getSupabaseConfig(env)
  
  const [copied, setCopied] = useState(false)
  const [customUrl, setCustomUrl] = useState(config.url)
  const [customKey, setCustomKey] = useState(config.key)

  const handleCopy = () => {
    navigator.clipboard.writeText(SQL_SCRIPT)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleConfigureDatabase = () => {
    handleCopy();
    const supabaseUrl = config.url;
    // Extract project ref from URL: https://[project-ref].supabase.co
    const projectRef = supabaseUrl.split('//')[1]?.split('.')[0];
    
    if (projectRef && !config.isCustom) {
      const sqlEditorUrl = `https://supabase.com/dashboard/project/${projectRef}/sql/new`;
      window.open(sqlEditorUrl, '_blank');
      alert('O script SQL foi copiado! O painel do Supabase foi aberto em uma nova aba. Vá em "SQL Editor", cole o script e clique em "Run".');
    } else {
      alert('O script SQL foi copiado! Vá ao seu painel do Supabase, acesse o "SQL Editor", cole o script e clique em "Run".');
    }
  }

  const [verifying, setVerifying] = useState(false);
  const handleVerifyIntegrity = async () => {
    setVerifying(true);
    const tables = ['users', 'clients', 'indicators', 'law_areas', 'products', 'contracts', 'installments', 'processes', 'bank_accounts', 'financial_categories', 'financial_transactions', 'audit_logs', 'system_settings', 'user_sessions'];
    const results = [];
    
    for (const table of tables) {
      const { error } = await supabase.from(table).select('count', { count: 'exact', head: true });
      results.push({ table, ok: !error });
    }
    
    const missing = results.filter(r => !r.ok).map(r => r.table);
    if (missing.length === 0) {
      alert('Integridade OK! Todas as tabelas foram encontradas.');
    } else {
      alert(`Atenção! As seguintes tabelas não foram encontradas: ${missing.join(', ')}. Por favor, execute o script SQL.`);
    }
    setVerifying(false);
  }

  const handleSaveConfig = () => {
    if (!customUrl || !customKey) {
      alert('Preencha a URL e a Chave.')
      return
    }
    localStorage.setItem(`custom_supabase_url_production`, customUrl)
    localStorage.setItem(`custom_supabase_key_production`, customKey)
    alert('Configuração salva com sucesso! A página será recarregada.')
    window.location.reload()
  }

  const handleClearConfig = () => {
    if (confirm('Tem certeza que deseja restaurar as configurações padrão?')) {
      localStorage.removeItem(`custom_supabase_url_production`)
      localStorage.removeItem(`custom_supabase_key_production`)
      alert('Configuração restaurada para o padrão! A página será recarregada.')
      window.location.reload()
    }
  }

  return (
    <div className="min-h-screen bg-slate-50 flex flex-col items-center justify-center p-4">
      <div className="max-w-4xl w-full mb-4 flex justify-start">
        <Link href="/" className="inline-flex items-center gap-2 px-4 py-2 bg-white border border-slate-200 text-slate-700 rounded-lg hover:bg-slate-50 transition-colors font-medium text-sm shadow-sm">
          <ArrowLeft size={16} />
          Voltar ao Início
        </Link>
      </div>
      <div className="max-w-4xl w-full bg-white rounded-2xl shadow-xl overflow-hidden border border-slate-200">
        <div className="bg-indigo-600 p-6 text-white flex items-center gap-4">
          <div className="bg-white/20 p-3 rounded-xl">
            <Database size={32} />
          </div>
          <div>
            <h1 className="text-2xl font-bold">Configuração do Banco de Dados</h1>
            <p className="text-indigo-100">Diagnóstico e Reparo de Estrutura</p>
          </div>
        </div>

        <div className="p-8 space-y-6">
          <div className="bg-slate-50 border border-slate-200 rounded-xl p-6 mb-6">
            <h2 className="text-lg font-bold text-slate-900 mb-4 flex items-center gap-2">
              <CheckCircle2 className="text-emerald-600" />
              Diagnóstico de Conexão
            </h2>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <p className="text-sm font-medium text-slate-500 uppercase tracking-wider mb-1">Ambiente Atual</p>
                <div className={`inline-flex items-center gap-2 px-3 py-1.5 rounded-lg font-bold text-sm ${
                  env === 'production' 
                    ? 'bg-indigo-100 text-indigo-700' 
                    : 'bg-amber-100 text-amber-700'
                }`}>
                  {env === 'production' ? 'PRODUÇÃO' : 'TESTES'}
                </div>
              </div>

              <div className="md:col-span-2">
                <p className="text-sm font-medium text-slate-500 uppercase tracking-wider mb-1">
                  URL do Supabase {config.isCustom ? '(Personalizada)' : '(Padrão)'}
                </p>
                <input 
                  type="text" 
                  value={customUrl} 
                  onChange={(e) => setCustomUrl(e.target.value)}
                  className="w-full px-4 py-2 border border-slate-200 rounded-xl focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 outline-none font-mono text-sm"
                  placeholder="https://sua-url.supabase.co"
                />
              </div>

              <div className="md:col-span-2">
                <p className="text-sm font-medium text-slate-500 uppercase tracking-wider mb-1">
                  Chave Anon {config.isCustom ? '(Personalizada)' : '(Padrão)'}
                </p>
                <input 
                  type="text" 
                  value={customKey} 
                  onChange={(e) => setCustomKey(e.target.value)}
                  className="w-full px-4 py-2 border border-slate-200 rounded-xl focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 outline-none font-mono text-sm"
                  placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                />
              </div>
            </div>

            <div className="mt-6 pt-6 border-t border-slate-200 flex flex-wrap gap-3">
              <button 
                onClick={handleSaveConfig}
                className="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors font-medium text-sm"
              >
                Salvar Configuração Personalizada
              </button>
              {config.isCustom && (
                <button 
                  onClick={handleClearConfig}
                  className="px-4 py-2 bg-rose-100 text-rose-700 rounded-lg hover:bg-rose-200 transition-colors font-medium text-sm"
                >
                  Restaurar Padrão
                </button>
              )}
              <div className="w-full my-2 border-t border-slate-100"></div>
              <button 
                onClick={handleVerifyIntegrity}
                disabled={verifying}
                className="px-4 py-2 bg-white border border-slate-300 text-slate-700 rounded-lg hover:bg-slate-50 transition-colors font-medium text-sm flex items-center gap-2"
              >
                {verifying ? <div className="w-4 h-4 border-2 border-indigo-600 border-t-transparent rounded-full animate-spin" /> : <Database size={16} />}
                Verificar Integridade das Tabelas
              </button>
              <button 
                onClick={handleConfigureDatabase}
                className="px-4 py-2 bg-emerald-600 text-white rounded-lg hover:bg-emerald-700 transition-colors font-medium text-sm flex items-center gap-2"
              >
                <CheckCircle2 size={16} />
                Configurar Banco de Dados (Abrir Supabase)
              </button>
            </div>
          </div>

          <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 flex gap-3 text-amber-800">
            <AlertTriangle className="shrink-0 mt-0.5" />
            <div>
              <p className="font-bold">Atenção: Tabelas não encontradas</p>
              <p className="text-sm mt-1">
                O sistema detectou que as tabelas necessárias para o funcionamento (Contas, Categorias, Clientes, etc.) não existem no banco de dados atual. 
                Isso é comum em novos ambientes de teste ou produção.
              </p>
            </div>
          </div>

          <div className="space-y-4">
            <h2 className="text-lg font-semibold text-slate-900">Como corrigir:</h2>
            <ol className="list-decimal list-inside space-y-2 text-slate-600 ml-2">
              <li>Copie o script SQL abaixo clicando no botão &quot;Copiar SQL&quot;.</li>
              <li>Acesse o painel do seu projeto Supabase (Produção ou Teste, dependendo de onde está o erro).</li>
              <li>Vá até a seção <strong>SQL Editor</strong>.</li>
              <li>Cole o script e clique em <strong>Run</strong>.</li>
              <li>Após a execução com sucesso, recarregue esta aplicação.</li>
            </ol>
          </div>

          <div className="relative">
            <div className="absolute top-4 right-4 z-10">
              <button 
                onClick={handleCopy}
                className={`flex items-center gap-2 px-4 py-2 rounded-lg font-bold transition-all shadow-sm ${
                  copied 
                    ? 'bg-emerald-500 text-white' 
                    : 'bg-white text-slate-700 hover:bg-slate-50 border border-slate-200'
                }`}
              >
                {copied ? <CheckCircle2 size={18} /> : <Copy size={18} />}
                {copied ? 'Copiado!' : 'Copiar SQL'}
              </button>
            </div>
            <pre className="bg-slate-900 text-slate-300 p-6 rounded-xl overflow-auto h-96 text-sm font-mono leading-relaxed border border-slate-800">
              {SQL_SCRIPT}
            </pre>
          </div>
        </div>
      </div>
    </div>
  )
}
