'use client';

import React, { useState, useEffect } from 'react';
import { Copy, CheckCircle2, AlertTriangle, Database, Save, RotateCcw, Server, ShieldCheck, Trash2, Loader2, Activity } from 'lucide-react';
import { supabase, getSupabaseConfig } from '@/lib/supabase';
import { getAppEnv } from '@/lib/env';
import { toast } from 'sonner';

const SQL_SCRIPT = `-- 1. Users Table (RBAC)
CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  "canAccessDashboard" BOOLEAN DEFAULT TRUE,
  "canAccessClients" BOOLEAN DEFAULT FALSE,
  "canAccessProcesses" BOOLEAN DEFAULT FALSE,
  "canAccessFinance" BOOLEAN DEFAULT FALSE,
  "canAccessCashFlow" BOOLEAN DEFAULT FALSE,
  "canAccessProducts" BOOLEAN DEFAULT FALSE,
  "canAccessIndicators" BOOLEAN DEFAULT FALSE,
  "canAccessReports" BOOLEAN DEFAULT FALSE,
  "canAccessAudit" BOOLEAN DEFAULT FALSE,
  "canAccessUsers" BOOLEAN DEFAULT FALSE,
  "canAccessDocuments" BOOLEAN DEFAULT FALSE,
  "canAccessSettings" BOOLEAN DEFAULT FALSE,
  "canAccessProdEnv" BOOLEAN DEFAULT TRUE,
  "canAccessTestEnv" BOOLEAN DEFAULT FALSE,
  is_superadmin BOOLEAN DEFAULT FALSE,
  expiration_date DATE,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add columns if they don't exist (for existing databases)
DO $body$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessDashboard') THEN
      ALTER TABLE users ADD COLUMN "canAccessDashboard" BOOLEAN DEFAULT TRUE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessClients') THEN
      ALTER TABLE users ADD COLUMN "canAccessClients" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessProcesses') THEN
      ALTER TABLE users ADD COLUMN "canAccessProcesses" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessFinance') THEN
      ALTER TABLE users ADD COLUMN "canAccessFinance" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessCashFlow') THEN
      ALTER TABLE users ADD COLUMN "canAccessCashFlow" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessProducts') THEN
      ALTER TABLE users ADD COLUMN "canAccessProducts" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessIndicators') THEN
      ALTER TABLE users ADD COLUMN "canAccessIndicators" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessReports') THEN
      ALTER TABLE users ADD COLUMN "canAccessReports" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessAudit') THEN
      ALTER TABLE users ADD COLUMN "canAccessAudit" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessUsers') THEN
      ALTER TABLE users ADD COLUMN "canAccessUsers" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessDocuments') THEN
      ALTER TABLE users ADD COLUMN "canAccessDocuments" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessSettings') THEN
      ALTER TABLE users ADD COLUMN "canAccessSettings" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessProdEnv') THEN
      ALTER TABLE users ADD COLUMN "canAccessProdEnv" BOOLEAN DEFAULT TRUE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'canAccessTestEnv') THEN
      ALTER TABLE users ADD COLUMN "canAccessTestEnv" BOOLEAN DEFAULT FALSE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'is_superadmin') THEN
      ALTER TABLE users ADD COLUMN is_superadmin BOOLEAN DEFAULT FALSE;
  END IF;
END $body$;

-- 2. Clients Table
CREATE TABLE IF NOT EXISTS clients (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  address TEXT,
  "addressNumber" TEXT,
  "addressComplement" TEXT,
  neighborhood TEXT,
  city TEXT,
  uf TEXT,
  cep TEXT,
  status TEXT DEFAULT 'Ativo',
  type TEXT DEFAULT 'Pessoa Física',
  document TEXT,
  "inssPassword" TEXT,
  "civilStatus" TEXT,
  profession TEXT,
  "birthDate" DATE,
  "pisNisNit" TEXT,
  "contractSigned" BOOLEAN DEFAULT FALSE,
  "proxySigned" BOOLEAN DEFAULT FALSE,
  "isMinor" BOOLEAN DEFAULT FALSE,
  "legalRepresentative" TEXT,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(document, environment)
);

-- 3. Indicators Table
CREATE TABLE IF NOT EXISTS indicators (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  phone TEXT,
  cpf TEXT,
  "pixKey" TEXT,
  email TEXT,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(cpf, environment)
);

-- 4. Law Areas Table
CREATE TABLE IF NOT EXISTS law_areas (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(name, environment)
);

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  law_area_id BIGINT REFERENCES law_areas(id) ON DELETE SET NULL,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Contracts Table
CREATE TABLE IF NOT EXISTS contracts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  product TEXT DEFAULT 'Não informado',
  "lawArea" TEXT DEFAULT 'Não informada',
  status TEXT DEFAULT 'Aberto', -- 'Aberto', 'Parcial', 'Quitado', 'Cancelado'
  "launchDate" DATE,
  "contractDate" DATE,
  "processNumber" TEXT,
  "contractValue" DECIMAL(12,2) NOT NULL DEFAULT 0,
  "paymentMethod" TEXT, -- 'À vista', 'Parcelado'
  "installmentsCount" INTEGER DEFAULT 1,
  "isProBono" BOOLEAN DEFAULT FALSE,
  "isFinanced" BOOLEAN DEFAULT FALSE,
  "contractSigned" BOOLEAN DEFAULT FALSE,
  "proxySigned" BOOLEAN DEFAULT FALSE,
  "inssProtocol" TEXT,
  "gpsGenerated" BOOLEAN DEFAULT FALSE,
  "gpsPaid" BOOLEAN DEFAULT FALSE,
  "inssDeferred" BOOLEAN DEFAULT FALSE,
  "childbirthDate" DATE,
  indicator_id BIGINT REFERENCES indicators(id) ON DELETE SET NULL,
  "commissionPercent" DECIMAL(5,2) DEFAULT 0,
  "commissionValue" DECIMAL(12,2) DEFAULT 0,
  "commissionPaid" BOOLEAN DEFAULT FALSE,
  "amountReceivable" DECIMAL(12,2) DEFAULT 0,
  "amountReceived" DECIMAL(12,2) DEFAULT 0,
  observations TEXT,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Installments Table
CREATE TABLE IF NOT EXISTS installments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  contract_id BIGINT REFERENCES contracts(id) ON DELETE CASCADE,
  "installmentNumber" INTEGER NOT NULL,
  "dueDate" DATE NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  "amountPaid" DECIMAL(12,2) DEFAULT 0,
  status TEXT DEFAULT 'Aberto', -- 'Aberto', 'Parcial', 'Quitado', 'Cancelado', 'Prorrogada', 'Atrasada'
  interest DECIMAL(12,2) DEFAULT 0,
  fine DECIMAL(12,2) DEFAULT 0,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Processes Table (Legacy/External Tracking)
CREATE TABLE IF NOT EXISTS processes (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  number TEXT NOT NULL,
  court TEXT,
  priority TEXT,
  client TEXT,
  type TEXT,
  status TEXT,
  "last_update" TEXT,
  "deadline_date" DATE,
  history JSONB DEFAULT '[]',
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(number, environment)
);

-- 9. Bank Accounts Table
CREATE TABLE IF NOT EXISTS bank_accounts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  type TEXT DEFAULT 'Corrente',
  initial_balance DECIMAL(12,2) DEFAULT 0,
  current_balance DECIMAL(12,2) DEFAULT 0,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Financial Categories Table
CREATE TABLE IF NOT EXISTS financial_categories (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  type TEXT NOT NULL, -- 'income', 'expense'
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. Financial Transactions Table
CREATE TABLE IF NOT EXISTS financial_transactions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  amount DECIMAL(12,2) NOT NULL,
  type TEXT NOT NULL, -- 'income', 'expense', 'transfer'
  account_id BIGINT REFERENCES bank_accounts(id) ON DELETE CASCADE,
  category_id BIGINT REFERENCES financial_categories(id) ON DELETE SET NULL,
  description TEXT,
  destination_account_id BIGINT REFERENCES bank_accounts(id) ON DELETE CASCADE,
  environment TEXT DEFAULT 'production',
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 12. Audit Logs Table
CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  table_name TEXT NOT NULL,
  record_id TEXT NOT NULL,
  action TEXT NOT NULL,
  old_data JSONB,
  new_data JSONB,
  changed_fields JSONB,
  performed_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  performed_at TIMESTAMPTZ DEFAULT NOW(),
  environment TEXT DEFAULT 'production'
);

-- 13. Logical Isolation & Audit Columns (Fallback for existing tables)
DO $body$
DECLARE
  t text;
  tables text[] := ARRAY['users', 'clients', 'indicators', 'law_areas', 'products', 'contracts', 'installments', 'processes', 'bank_accounts', 'financial_categories', 'financial_transactions', 'payments', 'audit_logs', 'system_settings', 'user_sessions', 'login_attempts', 'notifications', 'process_deadlines'];
  BEGIN
  -- Fix identity columns to allow upserts
  FOREACH t IN ARRAY tables
  LOOP
    BEGIN
      EXECUTE format('ALTER TABLE %I ALTER COLUMN id SET GENERATED BY DEFAULT', t);
    EXCEPTION WHEN OTHERS THEN
      -- Ignore if already BY DEFAULT or column doesn't exist
    END;
  END LOOP;

  tables := ARRAY['users', 'clients', 'indicators', 'law_areas', 'products', 'contracts', 'installments', 'processes', 'bank_accounts', 'financial_categories', 'financial_transactions', 'payments', 'audit_logs', 'system_settings', 'user_sessions', 'notifications', 'process_deadlines'];
  FOREACH t IN ARRAY tables
  LOOP
    EXECUTE format('ALTER TABLE %I ADD COLUMN IF NOT EXISTS environment TEXT DEFAULT ''production''', t);
    EXECUTE format('UPDATE %I SET environment = ''production'' WHERE environment IS NULL', t);
    EXECUTE format('ALTER TABLE %I ADD COLUMN IF NOT EXISTS created_by BIGINT REFERENCES users(id) ON DELETE SET NULL', t);
    EXECUTE format('ALTER TABLE %I ADD COLUMN IF NOT EXISTS updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL', t);
  END LOOP;
END $body$;

-- 14. Audit System (Function & Triggers)
CREATE OR REPLACE FUNCTION log_audit_event()
RETURNS TRIGGER AS $func$
DECLARE
  old_data JSONB;
  new_data JSONB;
  changed_fields JSONB;
  performed_by BIGINT;
  record_id BIGINT;
  v_env TEXT;
BEGIN
  IF (TG_OP = 'INSERT') THEN
    new_data = to_jsonb(NEW);
    old_data = null;
    changed_fields = null;
    
    IF new_data ? 'created_by' THEN
      performed_by = (new_data->>'created_by')::BIGINT;
    ELSE
      performed_by = NULL;
    END IF;
    
    IF new_data ? 'environment' AND new_data->>'environment' IS NOT NULL THEN
      v_env = new_data->>'environment';
    ELSE
      v_env = 'production';
    END IF;
    
    record_id = (new_data->>'id')::TEXT;
  ELSIF (TG_OP = 'UPDATE') THEN
    new_data = to_jsonb(NEW);
    old_data = to_jsonb(OLD);
    SELECT jsonb_object_agg(key, value) INTO changed_fields
    FROM jsonb_each(new_data)
    WHERE old_data->key IS DISTINCT FROM value;
    
    IF new_data ? 'updated_by' THEN
      performed_by = (new_data->>'updated_by')::BIGINT;
    ELSIF new_data ? 'created_by' THEN
      performed_by = (new_data->>'created_by')::BIGINT;
    ELSE
      performed_by = NULL;
    END IF;
    
    IF new_data ? 'environment' AND new_data->>'environment' IS NOT NULL THEN
      v_env = new_data->>'environment';
    ELSE
      v_env = 'production';
    END IF;
    
    record_id = (new_data->>'id')::TEXT;
  ELSIF (TG_OP = 'DELETE') THEN
    new_data = null;
    old_data = to_jsonb(OLD);
    changed_fields = null;
    performed_by = NULL;
    
    IF old_data ? 'environment' AND old_data->>'environment' IS NOT NULL THEN
      v_env = old_data->>'environment';
    ELSE
      v_env = 'production';
    END IF;
    
    record_id = (old_data->>'id')::TEXT;
  END IF;

  INSERT INTO audit_logs (table_name, record_id, action, old_data, new_data, changed_fields, performed_by, environment)
  VALUES (TG_TABLE_NAME, record_id, TG_OP, old_data, new_data, changed_fields, performed_by, v_env);

  RETURN NULL;
END;
$func$ LANGUAGE plpgsql;

-- Apply Audit Triggers
DO $body$
DECLARE
  t text;
BEGIN
  FOR t IN SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_name != 'audit_logs' AND table_name != 'system_settings'
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS audit_%I ON %I', t, t);
    EXECUTE format('CREATE TRIGGER audit_%I AFTER INSERT OR UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION log_audit_event()', t, t);
  END LOOP;
END $body$;

-- 15. Cash Flow Balance System (Function & Trigger)
CREATE OR REPLACE FUNCTION update_account_balance()
RETURNS TRIGGER AS $func$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    IF (NEW.type = 'income') THEN
      UPDATE bank_accounts SET current_balance = current_balance + NEW.amount WHERE id = NEW.account_id;
    ELSIF (NEW.type = 'expense') THEN
      UPDATE bank_accounts SET current_balance = current_balance - NEW.amount WHERE id = NEW.account_id;
    ELSIF (NEW.type = 'transfer') THEN
      UPDATE bank_accounts SET current_balance = current_balance - NEW.amount WHERE id = NEW.account_id;
      UPDATE bank_accounts SET current_balance = current_balance + NEW.amount WHERE id = NEW.destination_account_id;
    END IF;
  ELSIF (TG_OP = 'DELETE') THEN
    IF (OLD.type = 'income') THEN
      UPDATE bank_accounts SET current_balance = current_balance - OLD.amount WHERE id = OLD.account_id;
    ELSIF (OLD.type = 'expense') THEN
      UPDATE bank_accounts SET current_balance = current_balance + OLD.amount WHERE id = OLD.account_id;
    ELSIF (OLD.type = 'transfer') THEN
      UPDATE bank_accounts SET current_balance = current_balance + OLD.amount WHERE id = OLD.account_id;
      UPDATE bank_accounts SET current_balance = current_balance - OLD.amount WHERE id = OLD.destination_account_id;
    END IF;
  ELSIF (TG_OP = 'UPDATE') THEN
    IF (OLD.type = 'income') THEN
      UPDATE bank_accounts SET current_balance = current_balance - OLD.amount WHERE id = OLD.account_id;
    ELSIF (OLD.type = 'expense') THEN
      UPDATE bank_accounts SET current_balance = current_balance + OLD.amount WHERE id = OLD.account_id;
    ELSIF (OLD.type = 'transfer') THEN
      UPDATE bank_accounts SET current_balance = current_balance + OLD.amount WHERE id = OLD.account_id;
      UPDATE bank_accounts SET current_balance = current_balance - OLD.amount WHERE id = OLD.destination_account_id;
    END IF;
    IF (NEW.type = 'income') THEN
      UPDATE bank_accounts SET current_balance = current_balance + NEW.amount WHERE id = NEW.account_id;
    ELSIF (NEW.type = 'expense') THEN
      UPDATE bank_accounts SET current_balance = current_balance - NEW.amount WHERE id = NEW.account_id;
    ELSIF (NEW.type = 'transfer') THEN
      UPDATE bank_accounts SET current_balance = current_balance - NEW.amount WHERE id = NEW.account_id;
      UPDATE bank_accounts SET current_balance = current_balance + NEW.amount WHERE id = NEW.destination_account_id;
    END IF;
  END IF;
  RETURN NULL;
END;
$func$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_balance ON financial_transactions;
CREATE TRIGGER trigger_update_balance AFTER INSERT OR UPDATE OR DELETE ON financial_transactions FOR EACH ROW EXECUTE FUNCTION update_account_balance();

-- 16. Row Level Security (RLS) & Policies
DO $body$
DECLARE
  t text;
BEGIN
  FOR t IN SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    
    IF t != 'users' THEN
      EXECUTE format('DROP POLICY IF EXISTS "Allow all access to %I" ON %I', t, t);
      EXECUTE format('CREATE POLICY "Allow all access to %I" ON %I FOR ALL USING (true) WITH CHECK (true)', t, t);
    END IF;
  END LOOP;
  
  -- Specific policies for users table
  EXECUTE 'DROP POLICY IF EXISTS "Allow all access to users" ON users';
  EXECUTE 'DROP POLICY IF EXISTS "Users can read users" ON users';
  EXECUTE 'DROP POLICY IF EXISTS "Users can insert users" ON users';
  EXECUTE 'DROP POLICY IF EXISTS "Superadmin protected update" ON users';
  EXECUTE 'DROP POLICY IF EXISTS "Superadmin protected delete" ON users';
  
  EXECUTE 'CREATE POLICY "Users can read users" ON users FOR SELECT USING (true)';
  EXECUTE 'CREATE POLICY "Users can insert users" ON users FOR INSERT WITH CHECK ((SELECT is_superadmin FROM users WHERE email = auth.jwt()->>''email'') = TRUE OR is_superadmin IS NOT TRUE)';
  EXECUTE 'CREATE POLICY "Superadmin protected update" ON users FOR UPDATE USING ((SELECT is_superadmin FROM users WHERE email = auth.jwt()->>''email'') = TRUE OR is_superadmin IS NOT TRUE)';
  EXECUTE 'CREATE POLICY "Superadmin protected delete" ON users FOR DELETE USING ((SELECT is_superadmin FROM users WHERE email = auth.jwt()->>''email'') = TRUE OR is_superadmin IS NOT TRUE)';
END $body$;

-- Fix specific RLS for user_sessions that might have been overridden by audit_hardening.sql
DROP POLICY IF EXISTS "Enable read access for all users" ON user_sessions;
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON user_sessions;
DROP POLICY IF EXISTS "Enable update for authenticated users" ON user_sessions;
DROP POLICY IF EXISTS "Admin access for user_sessions" ON public.user_sessions;
DROP POLICY IF EXISTS "User access for user_sessions" ON public.user_sessions;
DROP POLICY IF EXISTS "Public access for user_sessions" ON public.user_sessions;

CREATE POLICY "Enable read access for all users" ON user_sessions FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON user_sessions FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON user_sessions FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON user_sessions FOR DELETE USING (true);

-- 17. Default Data
INSERT INTO users (name, email, password, "canAccessClients", "canAccessProcesses", "canAccessFinance", "canAccessCashFlow", "canAccessProducts", "canAccessIndicators", "canAccessReports", "canAccessAudit", "canAccessUsers", "canAccessDocuments", "canAccessSettings", "canAccessDashboard", "canAccessProdEnv", "canAccessTestEnv")
VALUES ('Administrador', 'admin@admin.com', '$2b$10$9PKydAgjkh6urDnoQ0TsZ.6MDwkQ4TqG7vk/hRyzjur0jfV4ofKVu', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE)
ON CONFLICT (email) DO UPDATE SET
  "canAccessClients" = TRUE,
  "canAccessProcesses" = TRUE,
  "canAccessFinance" = TRUE,
  "canAccessCashFlow" = TRUE,
  "canAccessProducts" = TRUE,
  "canAccessIndicators" = TRUE,
  "canAccessReports" = TRUE,
  "canAccessAudit" = TRUE,
  "canAccessUsers" = TRUE,
  "canAccessDocuments" = TRUE,
  "canAccessSettings" = TRUE,
  "canAccessDashboard" = TRUE,
  "canAccessProdEnv" = TRUE,
  "canAccessTestEnv" = TRUE;

-- 18. System Settings Table (Centralized Configuration)
CREATE TABLE IF NOT EXISTS system_settings (
  key VARCHAR(255) NOT NULL,
  value JSONB NOT NULL,
  description TEXT,
  category VARCHAR(50),
  environment VARCHAR(50) NOT NULL DEFAULT 'production',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  PRIMARY KEY (key, environment)
);

-- Enable RLS
ALTER TABLE system_settings ENABLE ROW LEVEL SECURITY;

-- Policies
DO $body$
BEGIN
  DROP POLICY IF EXISTS "Everyone can read settings" ON system_settings;
  CREATE POLICY "Everyone can read settings" ON system_settings FOR SELECT USING (true);
  
  DROP POLICY IF EXISTS "Authenticated users can update settings" ON system_settings;
  CREATE POLICY "Authenticated users can update settings" ON system_settings FOR ALL USING (true) WITH CHECK (true);
END $body$;

-- Default Data
INSERT INTO system_settings (key, value, description, category, environment)
VALUES
  ('session_timeout', '{"enabled": false, "minutes": 30, "warning_minutes": 5}', 'Configuração de timeout de sessão', 'security', 'production'),
  ('maintenance_mode', '{"enabled": false}', 'Modo de manutenção do sistema', 'system', 'production'),
  ('general_preferences', '{"timezone": "America/Sao_Paulo", "date_format": "DD/MM/YYYY"}', 'Preferências gerais de data e hora', 'general', 'production'),
  ('appearance', '{"theme": "system", "primary_color": "indigo"}', 'Aparência e tema do sistema', 'appearance', 'production')
ON CONFLICT (key, environment) DO NOTHING;

-- Enable Realtime for system_settings
DO $body$
BEGIN
  -- 1. Create publication if it doesn't exist
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;

  -- 2. Add table to publication
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE system_settings;
  EXCEPTION
    WHEN duplicate_object THEN
      NULL; -- Table already in publication
    WHEN OTHERS THEN
      NULL; -- Other errors (e.g. publication is FOR ALL TABLES)
  END;
END $body$;

-- 21. Security & Performance Improvements (Indexes & Constraints)
-- Indexes for Foreign Keys and Environment
CREATE INDEX IF NOT EXISTS idx_users_environment ON users(environment);
CREATE INDEX IF NOT EXISTS idx_clients_environment ON clients(environment);
CREATE INDEX IF NOT EXISTS idx_contracts_client_id ON contracts(client_id);
CREATE INDEX IF NOT EXISTS idx_contracts_environment ON contracts(environment);
CREATE INDEX IF NOT EXISTS idx_installments_contract_id ON installments(contract_id);
CREATE INDEX IF NOT EXISTS idx_installments_environment ON installments(environment);
CREATE INDEX IF NOT EXISTS idx_transactions_account_id ON financial_transactions(account_id);
CREATE INDEX IF NOT EXISTS idx_transactions_environment ON financial_transactions(environment);
CREATE INDEX IF NOT EXISTS idx_audit_logs_environment ON audit_logs(environment);
CREATE INDEX IF NOT EXISTS idx_audit_logs_record_id ON audit_logs(record_id);

-- Data Integrity Constraints
DO $body$
BEGIN
  BEGIN
    ALTER TABLE clients ADD CONSTRAINT check_client_status CHECK (status IN ('Ativo', 'Inativo', 'Bloqueado'));
  EXCEPTION WHEN duplicate_object THEN NULL; END;
  
  BEGIN
    ALTER TABLE contracts DROP CONSTRAINT IF EXISTS check_contract_status;
    ALTER TABLE contracts ADD CONSTRAINT check_contract_status CHECK (status IN ('Aberto', 'Parcial', 'Quitado', 'Cancelado', 'Estornado'));
  EXCEPTION WHEN OTHERS THEN NULL; END;
  
  BEGIN
    ALTER TABLE installments DROP CONSTRAINT IF EXISTS check_installment_status;
    ALTER TABLE installments ADD CONSTRAINT check_installment_status CHECK (status IN ('Aberto', 'Parcial', 'Quitado', 'Cancelado', 'Prorrogada', 'Atrasada', 'Estornado'));
  EXCEPTION WHEN OTHERS THEN NULL; END;
  
  BEGIN
    ALTER TABLE financial_transactions ADD CONSTRAINT check_transaction_type CHECK (type IN ('income', 'expense', 'transfer'));
  EXCEPTION WHEN duplicate_object THEN NULL; END;
END $body$;

-- 22. RBAC Architecture (Roles & Permissions)
CREATE TABLE IF NOT EXISTS roles (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  description TEXT,
  environment TEXT DEFAULT 'production',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(name, environment)
);

CREATE TABLE IF NOT EXISTS permissions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS role_permissions (
  role_id BIGINT REFERENCES roles(id) ON DELETE CASCADE,
  permission_id BIGINT REFERENCES permissions(id) ON DELETE CASCADE,
  PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS user_roles (
  user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  role_id BIGINT REFERENCES roles(id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, role_id)
);

-- Enable RLS for new tables
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;

-- Basic Policies for RBAC tables
DO $body$
DECLARE
  t text;
BEGIN
  FOR t IN SELECT unnest(ARRAY['roles', 'permissions', 'role_permissions', 'user_roles'])
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS "Allow all access to %I" ON %I', t, t);
    EXECUTE format('CREATE POLICY "Allow all access to %I" ON %I FOR ALL USING (true) WITH CHECK (true)', t, t);
  END LOOP;
END $body$;

-- Default Roles & Permissions Setup
INSERT INTO permissions (slug, description) VALUES
  ('access_dashboard', 'Acesso ao Painel'),
  ('access_clients', 'Acesso a Clientes'),
  ('access_processes', 'Acesso a Processos'),
  ('access_finance', 'Acesso ao Financeiro'),
  ('access_cashflow', 'Acesso ao Fluxo de Caixa'),
  ('access_products', 'Acesso a Produtos'),
  ('access_indicators', 'Acesso a Indicadores'),
  ('access_reports', 'Acesso a Relatórios'),
  ('access_audit', 'Acesso a Auditoria'),
  ('access_users', 'Acesso a Usuários'),
  ('access_settings', 'Acesso a Configurações'),
  ('access_prod_env', 'Acesso ao Ambiente de Produção'),
  ('access_test_env', 'Acesso ao Ambiente de Testes')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO roles (name, description, environment) VALUES
  ('Administrador', 'Acesso total ao sistema', 'production'),
  ('Advogado', 'Acesso a clientes e processos', 'production'),
  ('Financeiro', 'Acesso a financeiro e fluxo de caixa', 'production')
ON CONFLICT (name, environment) DO NOTHING;

-- Map Admin Role to All Permissions
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name = 'Administrador'
ON CONFLICT DO NOTHING;

-- 23. Database Integrity Check Function
CREATE OR REPLACE FUNCTION check_database_orphans()
RETURNS TABLE (
  table_name TEXT,
  foreign_key TEXT,
  parent_table TEXT,
  orphan_count BIGINT
) LANGUAGE plpgsql SECURITY DEFINER AS $func$
BEGIN
  RETURN QUERY
  SELECT 'financial_transactions'::TEXT, 'account_id'::TEXT, 'bank_accounts'::TEXT, count(*)::BIGINT
  FROM financial_transactions ft LEFT JOIN bank_accounts ba ON ft.account_id = ba.id WHERE ba.id IS NULL AND ft.account_id IS NOT NULL
  UNION ALL
  SELECT 'financial_transactions', 'category_id', 'financial_categories', count(*)
  FROM financial_transactions ft LEFT JOIN financial_categories fc ON ft.category_id = fc.id WHERE fc.id IS NULL AND ft.category_id IS NOT NULL
  UNION ALL
  SELECT 'financial_transactions', 'destination_account_id', 'bank_accounts', count(*)
  FROM financial_transactions ft LEFT JOIN bank_accounts ba ON ft.destination_account_id = ba.id WHERE ba.id IS NULL AND ft.destination_account_id IS NOT NULL
  UNION ALL
  SELECT 'contracts', 'client_id', 'clients', count(*)
  FROM contracts c LEFT JOIN clients cl ON c.client_id = cl.id WHERE cl.id IS NULL AND c.client_id IS NOT NULL
  UNION ALL
  SELECT 'contracts', 'product_id', 'products', count(*)
  FROM contracts c LEFT JOIN products p ON c.product_id = p.id WHERE p.id IS NULL AND c.product_id IS NOT NULL
  UNION ALL
  SELECT 'contracts', 'indicator_id', 'indicators', count(*)
  FROM contracts c LEFT JOIN indicators i ON c.indicator_id = i.id WHERE i.id IS NULL AND c.indicator_id IS NOT NULL
  UNION ALL
  SELECT 'installments', 'contract_id', 'contracts', count(*)
  FROM installments i LEFT JOIN contracts c ON i.contract_id = c.id WHERE c.id IS NULL AND i.contract_id IS NOT NULL
  UNION ALL
  SELECT 'products', 'law_area_id', 'law_areas', count(*)
  FROM products p LEFT JOIN law_areas la ON p.law_area_id = la.id WHERE la.id IS NULL AND p.law_area_id IS NOT NULL;
END;
$func$;
`;

export function SystemTab() {
  const [copySuccess, setCopySuccess] = useState(false);
  const [integrityStatus, setIntegrityStatus] = useState<'idle' | 'checking' | 'success' | 'error'>('idle');
  const [missingTables, setMissingTables] = useState<string[]>([]);
  const [customUrl, setCustomUrl] = useState('');
  const [customKey, setCustomKey] = useState('');
  const [saveStatus, setSaveStatus] = useState<'idle' | 'success' | 'error'>('idle');
  
  const [auditStartDate, setAuditStartDate] = useState('');
  const [auditEndDate, setAuditEndDate] = useState('');
  const [cleaningAudit, setCleaningAudit] = useState(false);
  const [integrityCheckResults, setIntegrityCheckResults] = useState<any[] | null>(null);
  const [checkingIntegrity, setCheckingIntegrity] = useState(false);

  const env = getAppEnv();

  useEffect(() => {
    // Load existing custom config if any
    const storedUrl = localStorage.getItem('custom_supabase_url_production');
    const storedKey = localStorage.getItem('custom_supabase_key_production');
    if (storedUrl) setCustomUrl(storedUrl);
    if (storedKey) setCustomKey(storedKey);
  }, []);

  const handleConfigureDatabase = () => {
    navigator.clipboard.writeText(SQL_SCRIPT).then(() => {
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 3000);
      window.open('https://supabase.com/dashboard/project/_/sql/new', '_blank');
    });
  };

  const checkTableExistence = async (tableName: string) => {
    const { error } = await supabase.from(tableName).select('id').limit(1);
    // If error code is 42P01 (undefined_table), table is missing.
    // However, supabase-js might return a generic error or different code depending on RLS.
    // A reliable way is to check if we get data or a specific error.
    if (error && error.code === '42P01') {
      return false;
    }
    // For system_settings, the primary key is (key, environment), so 'id' might not exist if I didn't add it.
    // Wait, I defined PK as (key, environment). I didn't add 'id'.
    // So select('id') will fail with column not found, not table not found.
    // I should select '*' or 'key'.
    if (tableName === 'system_settings') {
       const { error: err2 } = await supabase.from(tableName).select('key').limit(1);
       if (err2 && err2.code === '42P01') return false;
       return true;
    }
    return true;
  };

  const handleVerifyIntegrity = async () => {
    setIntegrityStatus('checking');
    setMissingTables([]);
    
    const tablesToCheck = [
      'users', 'clients', 'processes', 'contracts', 'installments', 
      'products', 'law_areas', 'indicators', 'bank_accounts', 
      'financial_categories', 'financial_transactions', 'audit_logs',
      'system_settings'
    ];
    
    const missing: string[] = [];

    try {
      for (const table of tablesToCheck) {
        const exists = await checkTableExistence(table);
        if (!exists) {
          missing.push(table);
        }
      }

      if (missing.length > 0) {
        setMissingTables(missing);
        setIntegrityStatus('error');
      } else {
        setIntegrityStatus('success');
      }
    } catch (error) {
      console.error('Error verifying integrity:', error);
      setIntegrityStatus('error');
    }
  };

  const saveSupabaseConfig = () => {
    try {
      if (customUrl) localStorage.setItem('custom_supabase_url_production', customUrl);
      else localStorage.removeItem('custom_supabase_url_production');
      
      if (customKey) localStorage.setItem('custom_supabase_key_production', customKey);
      else localStorage.removeItem('custom_supabase_key_production');

      setSaveStatus('success');
      setTimeout(() => {
        setSaveStatus('idle');
        window.location.reload(); // Reload to apply changes
      }, 1500);
    } catch (e) {
      setSaveStatus('error');
    }
  };

  const restoreDefaultSupabaseConfig = () => {
    localStorage.removeItem('custom_supabase_url_production');
    localStorage.removeItem('custom_supabase_key_production');
    setCustomUrl('');
    setCustomKey('');
    setSaveStatus('success');
    setTimeout(() => {
      setSaveStatus('idle');
      window.location.reload();
    }, 1500);
  };

  const handleCleanAudit = async () => {
    if (!auditStartDate || !auditEndDate) {
      toast.error('Selecione as datas de início e fim.');
      return;
    }

    if (new Date(auditStartDate) > new Date(auditEndDate)) {
      toast.error('A data de início não pode ser maior que a data de fim.');
      return;
    }

    if (!confirm('Tem certeza que deseja excluir os logs de auditoria neste período? Esta ação é irreversível.')) {
      return;
    }

    try {
      setCleaningAudit(true);
      const response = await fetch('/api/settings/audit/cleanup', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ startDate: auditStartDate, endDate: auditEndDate }),
      });

      const data = await response.json();

      if (response.ok) {
        toast.success(`Sucesso! ${data.count} registros foram excluídos.`);
        setAuditStartDate('');
        setAuditEndDate('');
      } else {
        toast.error(`Erro: ${data.error || 'Falha ao limpar logs.'}`);
      }
    } catch (error) {
      console.error('Error cleaning audit logs:', error);
      toast.error('Erro ao conectar com o servidor.');
    } finally {
      setCleaningAudit(false);
    }
  };

  const runIntegrityCheck = async () => {
    setCheckingIntegrity(true);
    setIntegrityCheckResults(null);
    try {
      const { data, error } = await supabase.rpc('check_database_orphans');
      
      if (error) {
        // Se a função não existir, o erro será retornado.
        if (error.message.includes('function check_database_orphans() does not exist')) {
            toast.error('A função de verificação não existe no banco. Por favor, atualize o banco de dados executando o script SQL acima.');
        } else {
            throw error;
        }
        return;
      }

      setIntegrityCheckResults(data);
      
      const totalOrphans = data.reduce((acc: number, curr: any) => acc + curr.orphan_count, 0);
      if (totalOrphans === 0) {
         toast.success('Banco de dados íntegro! Nenhum registro órfão encontrado.');
      } else {
         toast.warning(`${totalOrphans} registros órfãos encontrados. Verifique os detalhes.`);
      }

    } catch (error: any) {
      console.error('Error checking integrity:', error);
      toast.error('Erro ao verificar integridade: ' + (error.message || 'Erro desconhecido'));
    } finally {
      setCheckingIntegrity(false);
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-lg font-medium leading-6 text-slate-900">Sistema e Banco de Dados</h3>
        <p className="mt-1 text-sm text-slate-500">
          Ferramentas de diagnóstico, configuração de banco de dados e conexão.
        </p>
      </div>

      <div className="grid grid-cols-1 gap-6">
        {/* Database Configuration */}
        <div className="bg-white shadow sm:rounded-lg">
          <div className="px-4 py-5 sm:p-6">
            <h3 className="text-base font-semibold leading-6 text-slate-900 flex items-center gap-2">
              <Database className="h-5 w-5 text-indigo-600" />
              Configuração do Banco de Dados
            </h3>
            <div className="mt-2 max-w-xl text-sm text-slate-500">
              <p>
                Se você está vendo erros de &quot;tabela não encontrada&quot; ou está configurando o sistema pela primeira vez,
                utilize esta ferramenta para criar a estrutura necessária no Supabase.
              </p>
            </div>
            <div className="mt-5">
              <button
                type="button"
                onClick={handleConfigureDatabase}
                className="inline-flex items-center rounded-md bg-emerald-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-emerald-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-600"
              >
                {copySuccess ? <CheckCircle2 className="mr-2 h-4 w-4" /> : <Copy className="mr-2 h-4 w-4" />}
                {copySuccess ? 'Script Copiado!' : 'Configurar Banco de Dados (Abrir Supabase)'}
              </button>
              <p className="mt-2 text-xs text-slate-400">
                Isso copiará o script SQL e abrirá o editor do Supabase. Cole e execute o script lá.
              </p>
            </div>
          </div>
        </div>

        {/* Integrity Check */}
        <div className="bg-white shadow sm:rounded-lg">
          <div className="px-4 py-5 sm:p-6">
            <h3 className="text-base font-semibold leading-6 text-slate-900 flex items-center gap-2">
              <ShieldCheck className="h-5 w-5 text-indigo-600" />
              Verificação de Integridade
            </h3>
            <div className="mt-2 max-w-xl text-sm text-slate-500">
              <p>
                Verifique se todas as tabelas essenciais do sistema estão acessíveis e configuradas corretamente.
                Também verifica se existem registros órfãos (ex: transações sem conta bancária) que podem causar inconsistências.
              </p>
            </div>
            <div className="mt-5 flex flex-wrap gap-3">
              <button
                type="button"
                onClick={handleVerifyIntegrity}
                disabled={integrityStatus === 'checking'}
                className="inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-slate-900 shadow-sm ring-1 ring-inset ring-slate-300 hover:bg-slate-50 disabled:opacity-50"
              >
                {integrityStatus === 'checking' ? 'Verificando Tabelas...' : 'Verificar Tabelas'}
              </button>
              
              <button
                type="button"
                onClick={runIntegrityCheck}
                disabled={checkingIntegrity}
                className="inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-slate-900 shadow-sm ring-1 ring-inset ring-slate-300 hover:bg-slate-50 disabled:opacity-50"
              >
                {checkingIntegrity ? (
                    <>
                        <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                        Verificando Órfãos...
                    </>
                ) : (
                    <>
                        <Activity className="h-4 w-4 mr-2 text-slate-500" />
                        Verificar Registros Órfãos
                    </>
                )}
              </button>
            </div>

            {integrityStatus === 'success' && (
              <div className="mt-4 rounded-md bg-emerald-50 p-4">
                <div className="flex">
                  <div className="flex-shrink-0">
                    <CheckCircle2 className="h-5 w-5 text-emerald-400" aria-hidden="true" />
                  </div>
                  <div className="ml-3">
                    <h3 className="text-sm font-medium text-emerald-800">Tabelas OK</h3>
                    <div className="mt-2 text-sm text-emerald-700">
                      <p>Todas as tabelas essenciais foram encontradas.</p>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {integrityStatus === 'error' && (
              <div className="mt-4 rounded-md bg-red-50 p-4">
                <div className="flex">
                  <div className="flex-shrink-0">
                    <AlertTriangle className="h-5 w-5 text-red-400" aria-hidden="true" />
                  </div>
                  <div className="ml-3">
                    <h3 className="text-sm font-medium text-red-800">Problemas nas Tabelas</h3>
                    <div className="mt-2 text-sm text-red-700">
                      <p>As seguintes tabelas não foram encontradas ou não estão acessíveis:</p>
                      <ul role="list" className="list-disc space-y-1 pl-5 mt-1">
                        {missingTables.map(table => (
                          <li key={table}>{table}</li>
                        ))}
                      </ul>
                      <p className="mt-2 font-medium">Recomendação: Execute o script de &quot;Configurar Banco de Dados&quot; acima.</p>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {integrityCheckResults && (
                <div className="mt-6 border-t border-slate-100 pt-4">
                    <h4 className="text-sm font-medium text-slate-900 mb-3">Resultados do Diagnóstico de Órfãos</h4>
                    {integrityCheckResults.length === 0 || integrityCheckResults.every(r => r.orphan_count === 0) ? (
                        <div className="rounded-md bg-emerald-50 p-4">
                            <div className="flex">
                                <div className="flex-shrink-0">
                                    <CheckCircle2 className="h-5 w-5 text-emerald-400" aria-hidden="true" />
                                </div>
                                <div className="ml-3">
                                    <h3 className="text-sm font-medium text-emerald-800">Tudo certo!</h3>
                                    <div className="mt-2 text-sm text-emerald-700">
                                        <p>Nenhum registro órfão foi encontrado no banco de dados.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    ) : (
                        <div className="overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:rounded-lg">
                            <table className="min-w-full divide-y divide-slate-300">
                                <thead className="bg-slate-50">
                                    <tr>
                                        <th scope="col" className="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-slate-900 sm:pl-6">Tabela</th>
                                        <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-slate-900">Relação (FK)</th>
                                        <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-slate-900">Tabela Pai</th>
                                        <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-slate-900">Órfãos</th>
                                        <th scope="col" className="relative py-3.5 pl-3 pr-4 sm:pr-6">
                                            <span className="sr-only">Status</span>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-slate-200 bg-white">
                                    {integrityCheckResults.filter(r => r.orphan_count > 0).map((result, idx) => (
                                        <tr key={idx}>
                                            <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-slate-900 sm:pl-6">
                                                {result.table_name}
                                            </td>
                                            <td className="whitespace-nowrap px-3 py-4 text-sm text-slate-500">{result.foreign_key}</td>
                                            <td className="whitespace-nowrap px-3 py-4 text-sm text-slate-500">{result.parent_table}</td>
                                            <td className="whitespace-nowrap px-3 py-4 text-sm text-rose-600 font-bold">{result.orphan_count}</td>
                                            <td className="whitespace-nowrap px-3 py-4 text-sm text-slate-500">
                                                <span className="inline-flex items-center rounded-md bg-rose-50 px-2 py-1 text-xs font-medium text-rose-700 ring-1 ring-inset ring-rose-600/20">
                                                    Crítico
                                                </span>
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    )}
                </div>
            )}
          </div>
        </div>

        {/* Audit Cleanup */}
        <div className="bg-white shadow sm:rounded-lg border-l-4 border-amber-500">
          <div className="px-4 py-5 sm:p-6">
            <h3 className="text-base font-semibold leading-6 text-slate-900 flex items-center gap-2">
              <Trash2 className="h-5 w-5 text-amber-600" />
              Limpeza de Logs de Auditoria
            </h3>
            <div className="mt-2 max-w-xl text-sm text-slate-500">
              <p>
                Exclua registros antigos da tabela de auditoria para liberar espaço e otimizar o banco de dados.
                <strong className="block mt-1 text-amber-600">Atenção: Esta ação é irreversível.</strong>
              </p>
            </div>
            
            <div className="mt-5 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
              <div className="sm:col-span-3">
                <label htmlFor="audit-start-date" className="block text-sm font-medium leading-6 text-slate-900">
                  Data Início
                </label>
                <div className="mt-2">
                  <input
                    type="date"
                    id="audit-start-date"
                    value={auditStartDate}
                    onChange={(e) => setAuditStartDate(e.target.value)}
                    className="block w-full rounded-md border-0 py-1.5 text-slate-900 shadow-sm ring-1 ring-inset ring-slate-300 placeholder:text-slate-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                  />
                </div>
              </div>

              <div className="sm:col-span-3">
                <label htmlFor="audit-end-date" className="block text-sm font-medium leading-6 text-slate-900">
                  Data Fim
                </label>
                <div className="mt-2">
                  <input
                    type="date"
                    id="audit-end-date"
                    value={auditEndDate}
                    onChange={(e) => setAuditEndDate(e.target.value)}
                    className="block w-full rounded-md border-0 py-1.5 text-slate-900 shadow-sm ring-1 ring-inset ring-slate-300 placeholder:text-slate-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                  />
                </div>
              </div>
            </div>

            <div className="mt-5">
              <button
                type="button"
                onClick={handleCleanAudit}
                disabled={cleaningAudit || !auditStartDate || !auditEndDate}
                className="inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-red-600 shadow-sm ring-1 ring-inset ring-red-300 hover:bg-red-50 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {cleaningAudit ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Limpando...
                  </>
                ) : (
                  <>
                    <Trash2 className="mr-2 h-4 w-4" />
                    Excluir Logs no Período
                  </>
                )}
              </button>
            </div>
          </div>
        </div>

        {/* Connection Settings */}
        <div className="bg-white shadow sm:rounded-lg">
          <div className="px-4 py-5 sm:p-6">
            <h3 className="text-base font-semibold leading-6 text-slate-900 flex items-center gap-2">
              <Server className="h-5 w-5 text-indigo-600" />
              Conexão Supabase (Avançado)
            </h3>
            <div className="mt-2 max-w-xl text-sm text-slate-500">
              <p>
                Configure manualmente a URL e Chave do Supabase se necessário. 
                <strong className="text-amber-600 ml-1">Cuidado: Alterar isso pode quebrar o acesso ao sistema.</strong>
              </p>
            </div>
            
            <div className="mt-4 grid grid-cols-1 gap-y-4">
              <div>
                <label htmlFor="supabase-url" className="block text-sm font-medium leading-6 text-slate-900">
                  Supabase URL
                </label>
                <div className="mt-2">
                  <input
                    type="text"
                    name="supabase-url"
                    id="supabase-url"
                    value={customUrl}
                    onChange={(e) => setCustomUrl(e.target.value)}
                    placeholder={getSupabaseConfig(env).url}
                    className="block w-full rounded-md border-0 py-1.5 text-slate-900 shadow-sm ring-1 ring-inset ring-slate-300 placeholder:text-slate-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                  />
                </div>
              </div>

              <div>
                <label htmlFor="supabase-key" className="block text-sm font-medium leading-6 text-slate-900">
                  Supabase Anon Key
                </label>
                <div className="mt-2">
                  <input
                    type="password"
                    name="supabase-key"
                    id="supabase-key"
                    value={customKey}
                    onChange={(e) => setCustomKey(e.target.value)}
                    placeholder={getSupabaseConfig(env).key.substring(0, 10) + '...'}
                    className="block w-full rounded-md border-0 py-1.5 text-slate-900 shadow-sm ring-1 ring-inset ring-slate-300 placeholder:text-slate-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
                  />
                </div>
              </div>
            </div>

            <div className="mt-5 flex items-center gap-3">
              <button
                type="button"
                onClick={saveSupabaseConfig}
                className="inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
              >
                <Save className="mr-2 h-4 w-4" />
                Salvar Configuração
              </button>
              <button
                type="button"
                onClick={restoreDefaultSupabaseConfig}
                className="inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-slate-900 shadow-sm ring-1 ring-inset ring-slate-300 hover:bg-slate-50"
              >
                <RotateCcw className="mr-2 h-4 w-4" />
                Restaurar Padrão
              </button>
              {saveStatus === 'success' && (
                <span className="text-sm text-emerald-600 font-medium animate-fade-in">Salvo com sucesso! Recarregando...</span>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
